<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsPublishable>true</IsPublishable>
    <EnableContainer>true</EnableContainer>
    <ContainerRepository>eventstore-operations</ContainerRepository>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Hexalith.EventStore.Operations.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hexalith.EventStore.Admin.Abstractions\Hexalith.EventStore.Admin.Abstractions.csproj" />
    <ProjectReference Include="..\Hexalith.EventStore.ServiceDefaults\Hexalith.EventStore.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapr.AspNetCore" />
    <PackageReference Include="Dapr.Actors" />
    <PackageReference Include="Dapr.Actors.AspNetCore" />
  </ItemGroup>

</Project>
