apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: "TODO: Kafka broker addresses"
    - name: authType
      value: "TODO: none|password|mtls|oidc"
