apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: resiliency
spec:
  policies:
    retries:
      defaultRetry:
        policy: exponential
        maxInterval: 15s
        maxRetries: 10
    timeouts:
      daprSidecar:
        general: 5s
    circuitBreakers:
      defaultBreaker:
        maxRequests: 1
        interval: 60s
        timeout: 60s
        trip: consecutiveFailures > 5
  targets:
    apps:
      commandapi:
        retry: defaultRetry
        timeout: daprSidecar
        circuitBreaker: defaultBreaker
