apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.azure.cosmosdb
  version: v1
  metadata:
    - name: url
      value: "TODO: Cosmos DB account URL"
    - name: masterKey
      value: "TODO: Cosmos DB master key"
    - name: database
      value: "TODO: Database name"
    - name: collection
      value: "TODO: Collection name"
    - name: actorStateStore
      value: "true"
