<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup Condition="'$(UseCurrentSource)' != 'true'">
    <PackageReference Include="Hexalith.EventStore.Server" />
  </ItemGroup>
  <ItemGroup Condition="'$(UseCurrentSource)' == 'true'">
    <ProjectReference Include="$(EventStoreSourceRoot)/src/Hexalith.EventStore.Server/Hexalith.EventStore.Server.csproj" />
  </ItemGroup>
</Project>
