using Aspire.Hosting;
using Aspire.Hosting.ApplicationModel;

using CommunityToolkit.Aspire.Hosting.Dapr;

namespace Hexalith.EventStore.Aspire;

/// <summary>
/// Provides extension methods for adding the Hexalith EventStore topology
/// to an Aspire distributed application.
/// </summary>
public static class HexalithEventStoreExtensions {
    /// <summary>
    /// Adds the Hexalith EventStore topology to the distributed application builder.
    /// This provisions DAPR state store, DAPR pub/sub, and wires the CommandApi service
    /// with a DAPR sidecar, reducing boilerplate for consumers.
    /// Redis is provided by the DAPR initialization (`dapr init`) and is NOT managed by Aspire.
    /// The CommunityToolkit lifecycle hook auto-discovers DAPR's default component files
    /// at ~/.dapr/components/ which point to the dapr_redis container on localhost:6379.
    /// </summary>
    /// <param name="builder">The distributed application builder.</param>
    /// <param name="commandApi">The CommandApi project resource builder.</param>
    /// <param name="daprConfigPath">
    /// Path to the Dapr sidecar configuration file (access control policies, D4/FR34).
    /// When null, the sidecar starts without access control -- all service-to-service
    /// calls are allowed. This is a security risk in production environments.
    /// </param>
    /// <returns>A <see cref="HexalithEventStoreResources"/> containing the resource builders for further customization.</returns>
    public static HexalithEventStoreResources AddHexalithEventStore(
        this IDistributedApplicationBuilder builder,
        IResourceBuilder<ProjectResource> commandApi,
        string? daprConfigPath = null) {
        ArgumentNullException.ThrowIfNull(builder);
        ArgumentNullException.ThrowIfNull(commandApi);

        // DAPR components: auto-generated by the CommunityToolkit lifecycle hook.
        // The lifecycle hook discovers DAPR's default component YAML files at
        // ~/.dapr/components/ (created by `dapr init`), which connect to the
        // dapr_redis container on localhost:6379. No Aspire-managed Redis is needed.
        IResourceBuilder<IDaprComponentResource> stateStore = builder.AddDaprStateStore("statestore");
        IResourceBuilder<IDaprComponentResource> pubSub = builder.AddDaprPubSub("pubsub");

        // Wire up CommandApi with DAPR sidecar and component references.
        // AppPort is intentionally omitted so the CommunityToolkit auto-detects
        // the app's actual port from the Aspire resource model. Hardcoding AppPort
        // breaks Aspire Testing, which randomizes project ports.
        _ = commandApi
            .WithDaprSidecar(sidecar => sidecar
                .WithOptions(new DaprSidecarOptions {
                    AppId = "commandapi",
                    Config = daprConfigPath,
                })
                .WithReference(stateStore)
                .WithReference(pubSub));

        return new HexalithEventStoreResources(stateStore, pubSub, commandApi);
    }
}
