using System.Collections.Immutable;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Hexalith.EventStore.RestApi.Generators;

internal static class RestApiControllerEmitter
{
    public static RestApiGeneratedSource? Emit(
        RestApiOptions options,
        string controllerNamespace,
        ImmutableArray<RestApiMessageDescriptor> messages,
        Action<Diagnostic> reportDiagnostic)
    {
        ImmutableArray<RestApiMessageDescriptor> orderedMessages = messages
            .Where(static message => message.IsCommand || message.IsQuery)
            .OrderBy(static message => message.TypeName, StringComparer.Ordinal)
            .ToImmutableArray();
        if (orderedMessages.Length == 0)
        {
            return null;
        }

        var emittedMessages = ImmutableArray.CreateBuilder<RestApiMessageDescriptor>();
        foreach (RestApiMessageDescriptor message in orderedMessages)
        {
            RestApiRouteDescriptor route = GetRoute(message);
            if (RequiresRouteTenant(options) && !HasTenantRouteParameter(route))
            {
                reportDiagnostic(RestApiDiagnosticDescriptors.CreateMissingRouteTenant(message));
                continue;
            }

            if (message.IsQuery && IsAmbiguousQueryRoute(route))
            {
                reportDiagnostic(RestApiDiagnosticDescriptors.CreateAmbiguousQueryRoute(message));
                continue;
            }

            emittedMessages.Add(message);
        }

        if (emittedMessages.Count == 0)
        {
            return null;
        }

        string controllerName = GetControllerName(options);
        string hintScope = RestApiNameSanitizer.ToHintPart(controllerNamespace + "." + controllerName, "RestApi");
        string hintName = "Hexalith.EventStore.RestApi." + hintScope + ".Controller.g.cs";

        var builder = new StringBuilder();
        AppendHeader(builder, controllerNamespace);
        AppendControllerStart(builder, options, controllerName);
        foreach (RestApiMessageDescriptor message in emittedMessages)
        {
            if (message.IsCommand)
            {
                AppendCommandAction(builder, options, message);
            }

            if (message.IsQuery)
            {
                AppendQueryAction(builder, options, message);
            }
        }

        AppendHelpers(builder, options);
        builder.AppendLine("}");

        return new RestApiGeneratedSource(hintName, builder.ToString());
    }

    private static void AppendHeader(StringBuilder builder, string controllerNamespace)
    {
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using System.Globalization;");
        builder.AppendLine("using System.Linq;");
        builder.AppendLine("using System.Text.Json;");
        builder.AppendLine("using System.Text.Json.Serialization;");
        builder.AppendLine("using System.Threading;");
        builder.AppendLine("using System.Threading.Tasks;");
        builder.AppendLine();
        builder.AppendLine("using Hexalith.Commons.UniqueIds;");
        builder.AppendLine("using Hexalith.EventStore.Client.Gateway;");
        builder.AppendLine("using Hexalith.EventStore.Contracts.Commands;");
        builder.AppendLine("using Hexalith.EventStore.Contracts.Queries;");
        builder.AppendLine();
        builder.AppendLine("using Microsoft.AspNetCore.Authorization;");
        builder.AppendLine("using Microsoft.AspNetCore.Http;");
        builder.AppendLine("using Microsoft.AspNetCore.Mvc;");
        builder.AppendLine();
        builder.Append("namespace ").Append(controllerNamespace).AppendLine(";");
        builder.AppendLine();
    }

    private static void AppendControllerStart(StringBuilder builder, RestApiOptions options, string controllerName)
    {
        builder.AppendLine("[ApiController]");
        builder.AppendLine("[Authorize]");
        builder.Append("[Route(").Append(Literal(options.RoutePrefix)).AppendLine(")]");
        builder.Append("[Tags(").Append(Literal(GetTag(options))).AppendLine(")]");
        builder.AppendLine("[Consumes(\"application/json\")]");
        builder.Append("public sealed partial class ").Append(controllerName)
            .AppendLine("(IEventStoreGatewayClient gateway) : ControllerBase");
        builder.AppendLine("{");
        builder.AppendLine("    private static readonly JsonSerializerOptions JsonOptions = new JsonSerializerOptions(JsonSerializerDefaults.Web)");
        builder.AppendLine("    {");
        builder.AppendLine("        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,");
        builder.AppendLine("        Converters = { new JsonStringEnumConverter() },");
        builder.AppendLine("    };");
    }

    private static void AppendCommandAction(StringBuilder builder, RestApiOptions options, RestApiMessageDescriptor message)
    {
        RestApiRouteDescriptor route = GetRoute(message);
        ImmutableArray<RestApiRouteParameterDescriptor> routeParameters = route.Parameters;
        string methodName = RestApiNameSanitizer.ToIdentifier(message.SimpleTypeName + "Command", "Command", camelCase: false) + "Async";

        builder.AppendLine();
        AppendHttpAttribute(builder, route);
        builder.AppendLine("    [ProducesResponseType(typeof(SubmitCommandResponse), StatusCodes.Status202Accepted)]");
        builder.Append("    public async Task<IActionResult> ").Append(methodName).AppendLine("(");
        AppendRouteParameters(builder, message, routeParameters, trailingComma: true);
        builder.Append("        [FromBody] ").Append(message.FullyQualifiedTypeName).AppendLine("? body,");
        builder.AppendLine("        CancellationToken cancellationToken)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (body is null)");
        builder.AppendLine("        {");
        builder.AppendLine("            return CreateProblem(StatusCodes.Status400BadRequest, \"Bad Request\", \"Request body is required.\");");
        builder.AppendLine("        }");
        AppendTenantResolution(builder, options, route);
        AppendCommandRouteMismatchChecks(builder, message, route);
        builder.AppendLine();
        builder.AppendLine("        var request = new SubmitCommandRequest(");
        builder.AppendLine("            UniqueIdHelper.GenerateSortableUniqueStringId(),");
        builder.AppendLine("            tenant,");
        builder.Append("            ").Append(message.FullyQualifiedTypeName).AppendLine(".Domain,");
        builder.AppendLine("            body.AggregateId,");
        builder.Append("            ").Append(message.FullyQualifiedTypeName).AppendLine(".CommandType,");
        builder.AppendLine("            JsonSerializer.SerializeToElement(body, JsonOptions));");
        builder.AppendLine();
        builder.AppendLine("        try");
        builder.AppendLine("        {");
        builder.AppendLine("            SubmitCommandResponse response = await gateway");
        builder.AppendLine("                .SubmitCommandAsync(request, cancellationToken)");
        builder.AppendLine("                .ConfigureAwait(false);");
        builder.AppendLine();
        builder.AppendLine("            Response.Headers[\"Retry-After\"] = \"1\";");
        builder.AppendLine("            Response.Headers[\"Location\"] = \"/api/v1/commands/status/\" + Uri.EscapeDataString(response.CorrelationId);");
        builder.AppendLine("            return Accepted(response);");
        builder.AppendLine("        }");
        builder.AppendLine("        catch (EventStoreGatewayException ex)");
        builder.AppendLine("        {");
        builder.AppendLine("            return MapGatewayException(ex);");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
    }

    private static void AppendQueryAction(StringBuilder builder, RestApiOptions options, RestApiMessageDescriptor message)
    {
        RestApiRouteDescriptor route = GetRoute(message);
        ImmutableArray<RestApiRouteParameterDescriptor> routeParameters = route.Parameters;
        ImmutableArray<RestApiBindablePropertyDescriptor> queryParameters = GetQueryStringProperties(message, routeParameters);
        string methodName = RestApiNameSanitizer.ToIdentifier(message.SimpleTypeName + "Query", "Query", camelCase: false) + "Async";

        builder.AppendLine();
        AppendHttpAttribute(builder, route);
        builder.AppendLine("    [ProducesResponseType(StatusCodes.Status200OK)]");
        builder.AppendLine("    [ProducesResponseType(StatusCodes.Status304NotModified)]");
        builder.Append("    public async Task<IActionResult> ").Append(methodName).AppendLine("(");
        bool hasEarlierParameter = AppendRouteParameters(builder, message, routeParameters, trailingComma: routeParameters.Length > 0 || queryParameters.Length > 0);
        AppendQueryParameters(builder, queryParameters, hasEarlierParameter);
        builder.AppendLine("        [FromHeader(Name = \"If-None-Match\")] string? ifNoneMatch,");
        builder.AppendLine("        CancellationToken cancellationToken)");
        builder.AppendLine("    {");
        AppendTenantResolution(builder, options, route);
        AppendQueryPayload(builder, queryParameters);
        AppendQueryRouteValues(builder, route);
        builder.AppendLine();
        builder.AppendLine("        var request = new SubmitQueryRequest(");
        builder.AppendLine("            tenant,");
        builder.Append("            ").Append(message.FullyQualifiedTypeName).AppendLine(".Domain,");
        builder.AppendLine("            aggregateId,");
        builder.Append("            ").Append(message.FullyQualifiedTypeName).AppendLine(".QueryType,");
        builder.Append("            ").Append(message.FullyQualifiedTypeName).AppendLine(".ProjectionType,");
        builder.AppendLine("            payload,");
        builder.AppendLine("            entityId);");
        builder.AppendLine();
        builder.AppendLine("        try");
        builder.AppendLine("        {");
        builder.AppendLine("            EventStoreQueryResult result = await gateway");
        builder.AppendLine("                .SubmitQueryAsync(request, ifNoneMatch, cancellationToken)");
        builder.AppendLine("                .ConfigureAwait(false);");
        builder.AppendLine();
        builder.AppendLine("            if (!string.IsNullOrWhiteSpace(result.ETag))");
        builder.AppendLine("            {");
        builder.AppendLine("                Response.Headers[\"ETag\"] = result.ETag;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (result.IsNotModified)");
        builder.AppendLine("            {");
        builder.AppendLine("                return StatusCode(StatusCodes.Status304NotModified);");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return Ok(result.Payload);");
        builder.AppendLine("        }");
        builder.AppendLine("        catch (EventStoreGatewayException ex)");
        builder.AppendLine("        {");
        builder.AppendLine("            return MapGatewayException(ex);");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
    }

    private static void AppendHelpers(StringBuilder builder, RestApiOptions options)
    {
        builder.AppendLine();
        builder.AppendLine("    private ActionResult<string> ResolveTenant(string? tenant, string? tenantId)");
        builder.AppendLine("    {");
        builder.Append("        const string tenantSource = ").Append(Literal(options.TenantSource)).AppendLine(";");
        builder.AppendLine("        if (string.Equals(tenantSource, \"System\", StringComparison.Ordinal))");
        builder.AppendLine("        {");
        builder.AppendLine("            return \"system\";");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        if (string.Equals(tenantSource, \"Route\", StringComparison.Ordinal))");
        builder.AppendLine("        {");
        builder.AppendLine("            string? resolvedTenant = !string.IsNullOrWhiteSpace(tenant) ? tenant : tenantId;");
        builder.AppendLine("            return string.IsNullOrWhiteSpace(resolvedTenant)");
        builder.AppendLine("                ? CreateProblem(StatusCodes.Status400BadRequest, \"Bad Request\", \"Tenant route value is required.\")");
        builder.AppendLine("                : resolvedTenant;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        string[] tenants = User.FindAll(\"eventstore:tenant\")");
        builder.AppendLine("            .Select(static claim => claim.Value)");
        builder.AppendLine("            .Where(static value => !string.IsNullOrWhiteSpace(value))");
        builder.AppendLine("            .Distinct(StringComparer.Ordinal)");
        builder.AppendLine("            .ToArray();");
        builder.AppendLine("        if (tenants.Length == 0)");
        builder.AppendLine("        {");
        builder.AppendLine("            return CreateProblem(StatusCodes.Status403Forbidden, \"Forbidden\", \"A tenant claim is required.\");");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        return tenants.Length == 1");
        builder.AppendLine("            ? tenants[0]");
        builder.AppendLine("            : CreateProblem(StatusCodes.Status400BadRequest, \"Bad Request\", \"The tenant is ambiguous.\");");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private ObjectResult MapGatewayException(EventStoreGatewayException exception)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (!string.IsNullOrWhiteSpace(exception.RetryAfter))");
        builder.AppendLine("        {");
        builder.AppendLine("            Response.Headers[\"Retry-After\"] = exception.RetryAfter;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        var problem = new ProblemDetails");
        builder.AppendLine("        {");
        builder.AppendLine("            Status = exception.StatusCode,");
        builder.AppendLine("            Title = exception.Title,");
        builder.AppendLine("            Type = exception.Type,");
        builder.AppendLine("            Detail = exception.Detail,");
        builder.AppendLine("        };");
        builder.AppendLine();
        builder.AppendLine("        AddExtension(problem, \"correlationId\", exception.CorrelationId);");
        builder.AppendLine("        AddExtension(problem, \"tenantId\", exception.TenantId);");
        builder.AppendLine("        AddExtension(problem, \"reason\", exception.Reason);");
        builder.AppendLine("        AddExtension(problem, \"reasonCode\", exception.ReasonCode);");
        builder.AppendLine("        if (exception.Errors.Count > 0)");
        builder.AppendLine("        {");
        builder.AppendLine("            problem.Extensions[\"errors\"] = exception.Errors;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        foreach (KeyValuePair<string, JsonElement> extension in exception.Extensions)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (!problem.Extensions.ContainsKey(extension.Key))");
        builder.AppendLine("            {");
        builder.AppendLine("                problem.Extensions[extension.Key] = extension.Value;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        return new ObjectResult(problem)");
        builder.AppendLine("        {");
        builder.AppendLine("            StatusCode = exception.StatusCode,");
        builder.AppendLine("            ContentTypes = { \"application/problem+json\" },");
        builder.AppendLine("        };");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private static ObjectResult CreateProblem(int statusCode, string title, string detail)");
        builder.AppendLine("    {");
        builder.AppendLine("        var problem = new ProblemDetails");
        builder.AppendLine("        {");
        builder.AppendLine("            Status = statusCode,");
        builder.AppendLine("            Title = title,");
        builder.AppendLine("            Type = \"about:blank\",");
        builder.AppendLine("            Detail = detail,");
        builder.AppendLine("        };");
        builder.AppendLine();
        builder.AppendLine("        return new ObjectResult(problem)");
        builder.AppendLine("        {");
        builder.AppendLine("            StatusCode = statusCode,");
        builder.AppendLine("            ContentTypes = { \"application/problem+json\" },");
        builder.AppendLine("        };");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private static void AddExtension(ProblemDetails problem, string key, string? value)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (!string.IsNullOrWhiteSpace(value))");
        builder.AppendLine("        {");
        builder.AppendLine("            problem.Extensions[key] = value;");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
    }

    private static bool AppendRouteParameters(
        StringBuilder builder,
        RestApiMessageDescriptor message,
        ImmutableArray<RestApiRouteParameterDescriptor> routeParameters,
        bool trailingComma)
    {
        for (int i = 0; i < routeParameters.Length; i++)
        {
            RestApiRouteParameterDescriptor parameter = routeParameters[i];
            string parameterType = TryFindProperty(message, parameter.Name, out RestApiBindablePropertyDescriptor property)
                ? property.TypeName
                : "string";
            bool appendComma = trailingComma || i < routeParameters.Length - 1;
            builder.Append("        [FromRoute(Name = ").Append(Literal(parameter.Name)).Append(")] ")
                .Append(parameterType).Append(' ').Append(parameter.Identifier);
            builder.AppendLine(appendComma ? "," : string.Empty);
        }

        return routeParameters.Length > 0;
    }

    private static void AppendQueryParameters(
        StringBuilder builder,
        ImmutableArray<RestApiBindablePropertyDescriptor> queryParameters,
        bool hasEarlierParameter)
    {
        for (int i = 0; i < queryParameters.Length; i++)
        {
            RestApiBindablePropertyDescriptor parameter = queryParameters[i];
            string identifier = RestApiNameSanitizer.ToIdentifier(parameter.Name, parameter.Name, camelCase: true);
            builder.Append("        [FromQuery(Name = ").Append(Literal(parameter.Name)).Append(")] ")
                .Append(parameter.TypeName).Append(' ').Append(identifier).AppendLine(",");
            hasEarlierParameter = true;
        }
    }

    private static void AppendTenantResolution(StringBuilder builder, RestApiOptions options, RestApiRouteDescriptor route)
    {
        string tenantArgument = FindRouteParameterIdentifier(route, "tenant") ?? "null";
        string tenantIdArgument = FindRouteParameterIdentifier(route, "tenantId") ?? "null";
        builder.AppendLine();
        builder.Append("        ActionResult<string> tenantResult = ResolveTenant(")
            .Append(RequiresRouteTenant(options) ? tenantArgument : "null")
            .Append(", ")
            .Append(RequiresRouteTenant(options) ? tenantIdArgument : "null")
            .AppendLine(");");
        builder.AppendLine("        if (tenantResult.Result is not null)");
        builder.AppendLine("        {");
        builder.AppendLine("            return tenantResult.Result;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        string tenant = tenantResult.Value!;");
    }

    private static void AppendCommandRouteMismatchChecks(StringBuilder builder, RestApiMessageDescriptor message, RestApiRouteDescriptor route)
    {
        ImmutableArray<RestApiRouteParameterDescriptor> nonTenantParameters = GetNonTenantParameters(route);
        foreach (RestApiRouteParameterDescriptor parameter in nonTenantParameters)
        {
            string routeValue = "Convert.ToString(" + parameter.Identifier + ", CultureInfo.InvariantCulture)";
            if (string.Equals(parameter.Name, "aggregateId", StringComparison.OrdinalIgnoreCase))
            {
                builder.AppendLine();
                builder.Append("        if (!string.Equals(").Append(routeValue)
                    .AppendLine(", body.AggregateId, StringComparison.Ordinal))");
                builder.AppendLine("        {");
                builder.AppendLine("            return CreateProblem(StatusCodes.Status400BadRequest, \"Bad Request\", \"Route aggregate id does not match the command body.\");");
                builder.AppendLine("        }");
                continue;
            }

            if (TryFindProperty(message, parameter.Name, out RestApiBindablePropertyDescriptor property))
            {
                builder.AppendLine();
                builder.Append("        if (!string.Equals(").Append(routeValue)
                    .Append(", Convert.ToString(body.").Append(property.Name)
                    .AppendLine(", CultureInfo.InvariantCulture), StringComparison.Ordinal))");
                builder.AppendLine("        {");
                builder.Append("            return CreateProblem(StatusCodes.Status400BadRequest, \"Bad Request\", ")
                    .Append(Literal("Route value '" + parameter.Name + "' does not match the command body."))
                    .AppendLine(");");
                builder.AppendLine("        }");
                continue;
            }

            if (nonTenantParameters.Length == 1)
            {
                builder.AppendLine();
                builder.Append("        if (!string.Equals(").Append(routeValue)
                    .AppendLine(", body.AggregateId, StringComparison.Ordinal))");
                builder.AppendLine("        {");
                builder.AppendLine("            return CreateProblem(StatusCodes.Status400BadRequest, \"Bad Request\", \"Route aggregate id does not match the command body.\");");
                builder.AppendLine("        }");
            }
        }
    }

    private static void AppendQueryPayload(StringBuilder builder, ImmutableArray<RestApiBindablePropertyDescriptor> queryParameters)
    {
        builder.AppendLine();
        builder.AppendLine("        JsonElement? payload = null;");
        if (queryParameters.Length == 0)
        {
            return;
        }

        builder.AppendLine("        var payloadValues = new Dictionary<string, object?>(StringComparer.Ordinal)");
        builder.AppendLine("        {");
        foreach (RestApiBindablePropertyDescriptor parameter in queryParameters)
        {
            string identifier = RestApiNameSanitizer.ToIdentifier(parameter.Name, parameter.Name, camelCase: true);
            builder.Append("            [").Append(Literal(parameter.Name)).Append("] = ").Append(identifier).AppendLine(",");
        }

        builder.AppendLine("        };");
        builder.AppendLine("        payload = JsonSerializer.SerializeToElement(payloadValues, JsonOptions);");
    }

    private static void AppendQueryRouteValues(StringBuilder builder, RestApiRouteDescriptor route)
    {
        ImmutableArray<RestApiRouteParameterDescriptor> nonTenantParameters = GetNonTenantParameters(route);
        RestApiRouteParameterDescriptor? aggregateParameter = GetAggregateParameter(nonTenantParameters);
        RestApiRouteParameterDescriptor? entityParameter = GetEntityParameter(nonTenantParameters, aggregateParameter);
        string aggregateExpression = aggregateParameter.HasValue
            ? ToStringExpression(aggregateParameter.Value.Identifier, Literal("index"))
            : Literal("index");
        string entityExpression = entityParameter.HasValue
            ? ToStringExpression(entityParameter.Value.Identifier, "null")
            : "null";

        builder.AppendLine();
        builder.Append("        string aggregateId = ").Append(aggregateExpression).AppendLine(";");
        builder.Append("        string? entityId = ").Append(entityExpression).AppendLine(";");
    }

    private static void AppendHttpAttribute(StringBuilder builder, RestApiRouteDescriptor route)
    {
        builder.Append("    [").Append(ToHttpAttributeName(route.Verb)).Append('(')
            .Append(Literal(route.Template)).AppendLine(")]");
    }

    private static RestApiRouteDescriptor GetRoute(RestApiMessageDescriptor message)
    {
        if (message.Route.HasValue)
        {
            return message.Route.Value;
        }

        return new RestApiRouteDescriptor(message.IsCommand ? "Post" : "Get", string.Empty);
    }

    private static string GetControllerName(RestApiOptions options)
    {
        string source = !string.IsNullOrWhiteSpace(options.Tag)
            ? options.Tag
            : options.RoutePrefix;
        return RestApiNameSanitizer.ToTypeName(source, "RestApi") + "RestController";
    }

    private static string GetTag(RestApiOptions options)
        => !string.IsNullOrWhiteSpace(options.Tag)
            ? options.Tag
            : RestApiNameSanitizer.ToTypeName(options.RoutePrefix, "RestApi");

    private static string ToHttpAttributeName(string verb)
    {
        switch (verb)
        {
            case "Delete":
                return "HttpDelete";
            case "Get":
                return "HttpGet";
            case "Patch":
                return "HttpPatch";
            case "Put":
                return "HttpPut";
            case "Post":
            default:
                return "HttpPost";
        }
    }

    private static ImmutableArray<RestApiRouteParameterDescriptor> GetNonTenantParameters(RestApiRouteDescriptor route)
        => route.Parameters
            .Where(static parameter => !IsTenantParameter(parameter))
            .ToImmutableArray();

    private static RestApiRouteParameterDescriptor? GetAggregateParameter(ImmutableArray<RestApiRouteParameterDescriptor> nonTenantParameters)
    {
        foreach (RestApiRouteParameterDescriptor parameter in nonTenantParameters)
        {
            if (string.Equals(parameter.Name, "aggregateId", StringComparison.OrdinalIgnoreCase))
            {
                return parameter;
            }
        }

        return nonTenantParameters.Length == 1 ? nonTenantParameters[0] : null;
    }

    private static RestApiRouteParameterDescriptor? GetEntityParameter(
        ImmutableArray<RestApiRouteParameterDescriptor> nonTenantParameters,
        RestApiRouteParameterDescriptor? aggregateParameter)
    {
        foreach (RestApiRouteParameterDescriptor parameter in nonTenantParameters)
        {
            if (string.Equals(parameter.Name, "entityId", StringComparison.OrdinalIgnoreCase))
            {
                return parameter;
            }
        }

        foreach (RestApiRouteParameterDescriptor parameter in nonTenantParameters)
        {
            if (!aggregateParameter.HasValue || !parameter.Equals(aggregateParameter.Value))
            {
                return parameter;
            }
        }

        return null;
    }

    private static bool IsAmbiguousQueryRoute(RestApiRouteDescriptor route)
    {
        ImmutableArray<RestApiRouteParameterDescriptor> nonTenantParameters = GetNonTenantParameters(route);
        bool hasAggregateId = nonTenantParameters.Any(static parameter =>
            string.Equals(parameter.Name, "aggregateId", StringComparison.OrdinalIgnoreCase));
        bool hasEntityId = nonTenantParameters.Any(static parameter =>
            string.Equals(parameter.Name, "entityId", StringComparison.OrdinalIgnoreCase));
        if (hasAggregateId)
        {
            return false;
        }

        return hasEntityId ? nonTenantParameters.Length > 2 : nonTenantParameters.Length > 1;
    }

    private static ImmutableArray<RestApiBindablePropertyDescriptor> GetQueryStringProperties(
        RestApiMessageDescriptor message,
        ImmutableArray<RestApiRouteParameterDescriptor> routeParameters)
        => message.Properties
            .Where(property => !routeParameters.Any(routeParameter =>
                string.Equals(routeParameter.Name, property.Name, StringComparison.OrdinalIgnoreCase)))
            .ToImmutableArray();

    private static bool TryFindProperty(
        RestApiMessageDescriptor message,
        string routeParameterName,
        out RestApiBindablePropertyDescriptor property)
    {
        foreach (RestApiBindablePropertyDescriptor candidate in message.Properties)
        {
            if (string.Equals(candidate.Name, routeParameterName, StringComparison.OrdinalIgnoreCase))
            {
                property = candidate;
                return true;
            }
        }

        property = default;
        return false;
    }

    private static string? FindRouteParameterIdentifier(RestApiRouteDescriptor route, string name)
    {
        foreach (RestApiRouteParameterDescriptor parameter in route.Parameters)
        {
            if (string.Equals(parameter.Name, name, StringComparison.OrdinalIgnoreCase))
            {
                return parameter.Identifier;
            }
        }

        return null;
    }

    private static bool HasTenantRouteParameter(RestApiRouteDescriptor route)
        => route.Parameters.Any(static parameter => IsTenantParameter(parameter));

    private static bool IsTenantParameter(RestApiRouteParameterDescriptor parameter)
        => string.Equals(parameter.Name, "tenant", StringComparison.OrdinalIgnoreCase)
            || string.Equals(parameter.Name, "tenantId", StringComparison.OrdinalIgnoreCase);

    private static bool RequiresRouteTenant(RestApiOptions options)
        => string.Equals(options.TenantSource, "Route", StringComparison.Ordinal);

    private static string ToStringExpression(string identifier, string fallbackExpression)
        => "Convert.ToString(" + identifier + ", CultureInfo.InvariantCulture) ?? " + fallbackExpression;

    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, quote: true);
}
