using System.Collections.Immutable;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Hexalith.EventStore.RestApi.Generators;

internal static class RestApiControllerEmitter
{
    private static readonly string[] ReservedActionIdentifiers =
    [
        "__hexalithAggregateId",
        "__hexalithEntityId",
        "__hexalithPayload",
        "__hexalithPayloadValues",
        "__hexalithRequest",
        "__hexalithResponse",
        "__hexalithResult",
        "__hexalithTenant",
        "__hexalithTenantResult",
    ];

    public static RestApiGeneratedSource? Emit(
        RestApiOptions options,
        string controllerNamespace,
        ImmutableArray<RestApiMessageDescriptor> messages,
        Action<Diagnostic> reportDiagnostic)
    {
        ImmutableArray<RestApiMessageDescriptor> orderedMessages = messages
            .Where(static message => message.IsCommand || message.IsQuery)
            .OrderBy(static message => message.TypeName, StringComparer.Ordinal)
            .ToImmutableArray();
        if (orderedMessages.Length == 0)
        {
            return null;
        }

        var emittedMessages = ImmutableArray.CreateBuilder<RestApiMessageDescriptor>();
        var actionMethodNames = new HashSet<string>(StringComparer.Ordinal);
        var actionRoutes = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (RestApiMessageDescriptor message in orderedMessages)
        {
            RestApiRouteDescriptor route = GetRoute(message);
            ImmutableArray<RestApiRouteParameterDescriptor> effectiveRouteParameters = GetEffectiveRouteParameters(options, route);
            if (RequiresRouteTenant(options) && !HasTenantRouteParameter(effectiveRouteParameters))
            {
                reportDiagnostic(RestApiDiagnosticDescriptors.CreateMissingRouteTenant(message));
                continue;
            }

            if (TryFindDuplicateParameterIdentifier(message, effectiveRouteParameters, out string? duplicateRouteParameter))
            {
                reportDiagnostic(RestApiDiagnosticDescriptors.CreateDuplicateParameter(message, duplicateRouteParameter));
                continue;
            }

            if (message.IsQuery
                && TryFindUnsupportedQueryParameter(message, effectiveRouteParameters, out RestApiBindablePropertyDescriptor unsupportedProperty))
            {
                reportDiagnostic(RestApiDiagnosticDescriptors.CreateUnsupportedQueryParameter(message, unsupportedProperty));
                continue;
            }

            if (message.IsQuery && IsAmbiguousQueryRoute(effectiveRouteParameters))
            {
                reportDiagnostic(RestApiDiagnosticDescriptors.CreateAmbiguousQueryRoute(message));
                continue;
            }

            if (!TryReserveActionMethodNames(message, actionMethodNames, out string duplicateMethodName))
            {
                reportDiagnostic(RestApiDiagnosticDescriptors.CreateDuplicateParameter(message, duplicateMethodName));
                continue;
            }

            if (!TryReserveActionRoutes(options, message, route, actionRoutes, out string duplicateActionRoute))
            {
                reportDiagnostic(RestApiDiagnosticDescriptors.CreateDuplicateRoute(message, duplicateActionRoute));
                continue;
            }

            emittedMessages.Add(message);
        }

        if (emittedMessages.Count == 0)
        {
            return null;
        }

        string controllerName = GetControllerName(options);
        string hintScope = RestApiNameSanitizer.ToHintPart(controllerNamespace + "." + controllerName, "RestApi");
        string hintName = "Hexalith.EventStore.RestApi." + hintScope + ".Controller.g.cs";

        var builder = new StringBuilder();
        AppendHeader(builder, controllerNamespace);
        AppendControllerStart(builder, options, controllerName);
        foreach (RestApiMessageDescriptor message in emittedMessages)
        {
            if (message.IsCommand)
            {
                AppendCommandAction(builder, options, message);
            }

            if (message.IsQuery)
            {
                AppendQueryAction(builder, options, message);
            }
        }

        AppendHelpers(builder, options);
        builder.AppendLine("}");

        return new RestApiGeneratedSource(hintName, builder.ToString());
    }

    private static void AppendHeader(StringBuilder builder, string controllerNamespace)
    {
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using System.Globalization;");
        builder.AppendLine("using System.Linq;");
        builder.AppendLine("using System.Text.Json;");
        builder.AppendLine("using System.Text.Json.Serialization;");
        builder.AppendLine("using System.Threading;");
        builder.AppendLine("using System.Threading.Tasks;");
        builder.AppendLine();
        builder.AppendLine("using Hexalith.Commons.UniqueIds;");
        builder.AppendLine("using Hexalith.EventStore.Client.Gateway;");
        builder.AppendLine("using Hexalith.EventStore.Contracts.Commands;");
        builder.AppendLine("using Hexalith.EventStore.Contracts.Queries;");
        builder.AppendLine();
        builder.AppendLine("using Microsoft.AspNetCore.Authorization;");
        builder.AppendLine("using Microsoft.AspNetCore.Http;");
        builder.AppendLine("using Microsoft.AspNetCore.Mvc;");
        builder.AppendLine();
        builder.Append("namespace ").Append(controllerNamespace).AppendLine(";");
        builder.AppendLine();
    }

    private static void AppendControllerStart(StringBuilder builder, RestApiOptions options, string controllerName)
    {
        builder.AppendLine("[ApiController]");
        builder.AppendLine("[Authorize]");
        builder.Append("[Route(").Append(Literal(options.RoutePrefix)).AppendLine(")]");
        builder.Append("[Tags(").Append(Literal(GetTag(options))).AppendLine(")]");
        builder.AppendLine("[Consumes(\"application/json\")]");
        builder.Append("public sealed partial class ").Append(controllerName)
            .AppendLine("(IEventStoreGatewayClient gateway) : ControllerBase");
        builder.AppendLine("{");
        builder.AppendLine("    private static readonly JsonSerializerOptions JsonOptions = new JsonSerializerOptions(JsonSerializerDefaults.Web)");
        builder.AppendLine("    {");
        builder.AppendLine("        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,");
        builder.AppendLine("        Converters = { new JsonStringEnumConverter() },");
        builder.AppendLine("    };");
    }

    private static void AppendCommandAction(StringBuilder builder, RestApiOptions options, RestApiMessageDescriptor message)
    {
        RestApiRouteDescriptor route = GetRoute(message);
        ImmutableArray<RestApiRouteParameterDescriptor> routeParameters = GetEffectiveRouteParameters(options, route);
        string methodName = GetCommandMethodName(message);

        builder.AppendLine();
        AppendHttpAttribute(builder, route);
        builder.AppendLine("    [ProducesResponseType(typeof(SubmitCommandResponse), StatusCodes.Status202Accepted)]");
        builder.Append("    public async Task<IActionResult> ").Append(methodName).AppendLine("(");
        AppendRouteParameters(builder, message, routeParameters, trailingComma: true);
        builder.Append("        [FromBody] ").Append(message.FullyQualifiedTypeName).AppendLine("? body,");
        builder.AppendLine("        CancellationToken cancellationToken)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (body is null)");
        builder.AppendLine("        {");
        builder.AppendLine("            return CreateProblem(StatusCodes.Status400BadRequest, \"Bad Request\", \"Request body is required.\");");
        builder.AppendLine("        }");
        AppendTenantResolution(builder, options, routeParameters);
        AppendCommandRouteMismatchChecks(builder, message, routeParameters);
        builder.AppendLine();
        builder.AppendLine("        var __hexalithRequest = new SubmitCommandRequest(");
        builder.AppendLine("            UniqueIdHelper.GenerateSortableUniqueStringId(),");
        builder.AppendLine("            __hexalithTenant,");
        builder.Append("            ").Append(message.FullyQualifiedTypeName).AppendLine(".Domain,");
        builder.AppendLine("            body.AggregateId,");
        builder.Append("            ").Append(message.FullyQualifiedTypeName).AppendLine(".CommandType,");
        builder.AppendLine("            JsonSerializer.SerializeToElement(body, JsonOptions));");
        builder.AppendLine();
        builder.AppendLine("        try");
        builder.AppendLine("        {");
        builder.AppendLine("            SubmitCommandResponse __hexalithResponse = await gateway");
        builder.AppendLine("                .SubmitCommandAsync(__hexalithRequest, cancellationToken)");
        builder.AppendLine("                .ConfigureAwait(false);");
        builder.AppendLine();
        builder.AppendLine("            Response.Headers[\"Retry-After\"] = \"1\";");
        builder.AppendLine("            Response.Headers[\"Location\"] = \"/api/v1/commands/status/\" + Uri.EscapeDataString(__hexalithResponse.CorrelationId);");
        builder.AppendLine("            return Accepted(__hexalithResponse);");
        builder.AppendLine("        }");
        builder.AppendLine("        catch (EventStoreGatewayException ex)");
        builder.AppendLine("        {");
        builder.AppendLine("            return MapGatewayException(ex);");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
    }

    private static void AppendQueryAction(StringBuilder builder, RestApiOptions options, RestApiMessageDescriptor message)
    {
        RestApiRouteDescriptor route = GetRoute(message);
        ImmutableArray<RestApiRouteParameterDescriptor> routeParameters = GetEffectiveRouteParameters(options, route);
        ImmutableArray<RestApiBindablePropertyDescriptor> queryParameters = GetQueryStringProperties(message, routeParameters);
        string methodName = GetQueryMethodName(message);

        builder.AppendLine();
        AppendHttpAttribute(builder, route);
        builder.AppendLine("    [ProducesResponseType(StatusCodes.Status200OK)]");
        builder.AppendLine("    [ProducesResponseType(StatusCodes.Status304NotModified)]");
        builder.Append("    public async Task<IActionResult> ").Append(methodName).AppendLine("(");
        bool hasEarlierParameter = AppendRouteParameters(builder, message, routeParameters, trailingComma: routeParameters.Length > 0 || queryParameters.Length > 0);
        AppendQueryParameters(builder, queryParameters, hasEarlierParameter);
        builder.AppendLine("        [FromHeader(Name = \"If-None-Match\")] string? ifNoneMatch,");
        builder.AppendLine("        CancellationToken cancellationToken)");
        builder.AppendLine("    {");
        AppendTenantResolution(builder, options, routeParameters);
        AppendQueryPayload(builder, queryParameters);
        AppendQueryRouteValues(builder, routeParameters);
        builder.AppendLine();
        builder.AppendLine("        var __hexalithRequest = new SubmitQueryRequest(");
        builder.AppendLine("            __hexalithTenant,");
        builder.Append("            ").Append(message.FullyQualifiedTypeName).AppendLine(".Domain,");
        builder.AppendLine("            __hexalithAggregateId,");
        builder.Append("            ").Append(message.FullyQualifiedTypeName).AppendLine(".QueryType,");
        builder.Append("            ").Append(message.FullyQualifiedTypeName).AppendLine(".ProjectionType,");
        builder.AppendLine("            __hexalithPayload,");
        builder.AppendLine("            __hexalithEntityId);");
        builder.AppendLine();
        builder.AppendLine("        try");
        builder.AppendLine("        {");
        builder.AppendLine("            EventStoreQueryResult __hexalithResult = await gateway");
        builder.AppendLine("                .SubmitQueryAsync(__hexalithRequest, ifNoneMatch, cancellationToken)");
        builder.AppendLine("                .ConfigureAwait(false);");
        builder.AppendLine();
        builder.AppendLine("            if (!string.IsNullOrWhiteSpace(__hexalithResult.ETag))");
        builder.AppendLine("            {");
        builder.AppendLine("                Response.Headers[\"ETag\"] = FormatStrongETag(__hexalithResult.ETag);");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (__hexalithResult.IsNotModified)");
        builder.AppendLine("            {");
        builder.AppendLine("                return StatusCode(StatusCodes.Status304NotModified);");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return Ok(__hexalithResult.Payload);");
        builder.AppendLine("        }");
        builder.AppendLine("        catch (EventStoreGatewayException ex)");
        builder.AppendLine("        {");
        builder.AppendLine("            return MapGatewayException(ex);");
        builder.AppendLine("        }");
        builder.AppendLine("        catch (ArgumentException ex)");
        builder.AppendLine("        {");
        builder.AppendLine("            return CreateProblem(StatusCodes.Status400BadRequest, \"Bad Request\", ex.Message);");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
    }

    private static void AppendHelpers(StringBuilder builder, RestApiOptions options)
    {
        builder.AppendLine();
        builder.AppendLine("    private ActionResult<string> ResolveTenant(string? tenant, string? tenantId)");
        builder.AppendLine("    {");
        builder.Append("        const string tenantSource = ").Append(Literal(options.TenantSource)).AppendLine(";");
        builder.AppendLine("        if (string.Equals(tenantSource, \"System\", StringComparison.Ordinal))");
        builder.AppendLine("        {");
        builder.AppendLine("            return \"system\";");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        if (string.Equals(tenantSource, \"Route\", StringComparison.Ordinal))");
        builder.AppendLine("        {");
        builder.AppendLine("            string? resolvedTenant = !string.IsNullOrWhiteSpace(tenant) ? tenant : tenantId;");
        builder.AppendLine("            return string.IsNullOrWhiteSpace(resolvedTenant)");
        builder.AppendLine("                ? CreateProblem(StatusCodes.Status400BadRequest, \"Bad Request\", \"Tenant route value is required.\")");
        builder.AppendLine("                : resolvedTenant;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        string[] tenants = User.FindAll(\"eventstore:tenant\")");
        builder.AppendLine("            .Select(static claim => claim.Value)");
        builder.AppendLine("            .Where(static value => !string.IsNullOrWhiteSpace(value))");
        builder.AppendLine("            .Distinct(StringComparer.Ordinal)");
        builder.AppendLine("            .ToArray();");
        builder.AppendLine("        if (tenants.Length == 0)");
        builder.AppendLine("        {");
        builder.AppendLine("            return CreateProblem(StatusCodes.Status403Forbidden, \"Forbidden\", \"A tenant claim is required.\");");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        return tenants.Length == 1");
        builder.AppendLine("            ? tenants[0]");
        builder.AppendLine("            : CreateProblem(StatusCodes.Status400BadRequest, \"Bad Request\", \"The tenant is ambiguous.\");");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private ObjectResult MapGatewayException(EventStoreGatewayException exception)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (!string.IsNullOrWhiteSpace(exception.RetryAfter))");
        builder.AppendLine("        {");
        builder.AppendLine("            Response.Headers[\"Retry-After\"] = exception.RetryAfter;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        var problem = new ProblemDetails");
        builder.AppendLine("        {");
        builder.AppendLine("            Status = exception.StatusCode,");
        builder.AppendLine("            Title = exception.Title,");
        builder.AppendLine("            Type = exception.Type,");
        builder.AppendLine("            Detail = exception.Detail,");
        builder.AppendLine("        };");
        builder.AppendLine();
        builder.AppendLine("        AddExtension(problem, \"correlationId\", exception.CorrelationId);");
        builder.AppendLine("        AddExtension(problem, \"tenantId\", exception.TenantId);");
        builder.AppendLine("        AddExtension(problem, \"reason\", exception.Reason);");
        builder.AppendLine("        AddExtension(problem, \"reasonCode\", exception.ReasonCode);");
        builder.AppendLine("        if (exception.Errors.Count > 0)");
        builder.AppendLine("        {");
        builder.AppendLine("            problem.Extensions[\"errors\"] = exception.Errors;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        return new ObjectResult(problem)");
        builder.AppendLine("        {");
        builder.AppendLine("            StatusCode = exception.StatusCode,");
        builder.AppendLine("            ContentTypes = { \"application/problem+json\" },");
        builder.AppendLine("        };");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private static ObjectResult CreateProblem(int statusCode, string title, string detail)");
        builder.AppendLine("    {");
        builder.AppendLine("        var problem = new ProblemDetails");
        builder.AppendLine("        {");
        builder.AppendLine("            Status = statusCode,");
        builder.AppendLine("            Title = title,");
        builder.AppendLine("            Type = \"about:blank\",");
        builder.AppendLine("            Detail = detail,");
        builder.AppendLine("        };");
        builder.AppendLine();
        builder.AppendLine("        return new ObjectResult(problem)");
        builder.AppendLine("        {");
        builder.AppendLine("            StatusCode = statusCode,");
        builder.AppendLine("            ContentTypes = { \"application/problem+json\" },");
        builder.AppendLine("        };");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private static void AddExtension(ProblemDetails problem, string key, string? value)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (!string.IsNullOrWhiteSpace(value))");
        builder.AppendLine("        {");
        builder.AppendLine("            problem.Extensions[key] = value;");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private static string FormatStrongETag(string etag)");
        builder.AppendLine("    {");
        builder.AppendLine("        string value = etag.Trim();");
        builder.AppendLine("        return value.Length >= 2 && value[0] == '\"' && value[value.Length - 1] == '\"'");
        builder.AppendLine("            ? value");
        builder.AppendLine("            : \"\\\"\" + value.Trim('\"') + \"\\\"\";");
        builder.AppendLine("    }");
    }

    private static bool AppendRouteParameters(
        StringBuilder builder,
        RestApiMessageDescriptor message,
        ImmutableArray<RestApiRouteParameterDescriptor> routeParameters,
        bool trailingComma)
    {
        for (int i = 0; i < routeParameters.Length; i++)
        {
            RestApiRouteParameterDescriptor parameter = routeParameters[i];
            bool appendComma = trailingComma || i < routeParameters.Length - 1;
            builder.Append("        [FromRoute(Name = ").Append(Literal(parameter.Name)).Append(")] ")
                .Append("string ").Append(parameter.Identifier);
            builder.AppendLine(appendComma ? "," : string.Empty);
        }

        return routeParameters.Length > 0;
    }

    private static void AppendQueryParameters(
        StringBuilder builder,
        ImmutableArray<RestApiBindablePropertyDescriptor> queryParameters,
        bool hasEarlierParameter)
    {
        for (int i = 0; i < queryParameters.Length; i++)
        {
            RestApiBindablePropertyDescriptor parameter = queryParameters[i];
            string identifier = RestApiNameSanitizer.ToIdentifier(parameter.Name, parameter.Name, camelCase: true);
            builder.Append("        [FromQuery(Name = ").Append(Literal(parameter.Name)).Append(")] ")
                .Append(parameter.TypeName).Append(' ').Append(identifier).AppendLine(",");
            hasEarlierParameter = true;
        }
    }

    private static void AppendTenantResolution(
        StringBuilder builder,
        RestApiOptions options,
        ImmutableArray<RestApiRouteParameterDescriptor> routeParameters)
    {
        string tenantArgument = FindRouteParameterIdentifier(routeParameters, "tenant") ?? "null";
        string tenantIdArgument = FindRouteParameterIdentifier(routeParameters, "tenantId") ?? "null";
        builder.AppendLine();
        builder.Append("        ActionResult<string> __hexalithTenantResult = ResolveTenant(")
            .Append(RequiresRouteTenant(options) ? tenantArgument : "null")
            .Append(", ")
            .Append(RequiresRouteTenant(options) ? tenantIdArgument : "null")
            .AppendLine(");");
        builder.AppendLine("        if (__hexalithTenantResult.Result is not null)");
        builder.AppendLine("        {");
        builder.AppendLine("            return __hexalithTenantResult.Result;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        string __hexalithTenant = __hexalithTenantResult.Value!;");
    }

    private static void AppendCommandRouteMismatchChecks(
        StringBuilder builder,
        RestApiMessageDescriptor message,
        ImmutableArray<RestApiRouteParameterDescriptor> routeParameters)
    {
        ImmutableArray<RestApiRouteParameterDescriptor> nonTenantParameters = GetNonTenantParameters(routeParameters);
        foreach (RestApiRouteParameterDescriptor parameter in nonTenantParameters)
        {
            string routeValue = "Convert.ToString(" + parameter.Identifier + ", CultureInfo.InvariantCulture)";
            if (string.Equals(parameter.Name, "aggregateId", StringComparison.OrdinalIgnoreCase))
            {
                builder.AppendLine();
                builder.Append("        if (!string.Equals(").Append(routeValue)
                    .AppendLine(", body.AggregateId, StringComparison.Ordinal))");
                builder.AppendLine("        {");
                builder.AppendLine("            return CreateProblem(StatusCodes.Status400BadRequest, \"Bad Request\", \"Route aggregate id does not match the command body.\");");
                builder.AppendLine("        }");
                continue;
            }

            if (TryFindProperty(message, parameter.Name, out RestApiBindablePropertyDescriptor property))
            {
                builder.AppendLine();
                builder.Append("        if (!string.Equals(").Append(routeValue)
                    .Append(", Convert.ToString(body.").Append(property.Name)
                    .AppendLine(", CultureInfo.InvariantCulture), StringComparison.Ordinal))");
                builder.AppendLine("        {");
                builder.Append("            return CreateProblem(StatusCodes.Status400BadRequest, \"Bad Request\", ")
                    .Append(Literal("Route value '" + parameter.Name + "' does not match the command body."))
                    .AppendLine(");");
                builder.AppendLine("        }");
                continue;
            }

            if (nonTenantParameters.Length == 1)
            {
                builder.AppendLine();
                builder.Append("        if (!string.Equals(").Append(routeValue)
                    .AppendLine(", body.AggregateId, StringComparison.Ordinal))");
                builder.AppendLine("        {");
                builder.AppendLine("            return CreateProblem(StatusCodes.Status400BadRequest, \"Bad Request\", \"Route aggregate id does not match the command body.\");");
                builder.AppendLine("        }");
            }
        }
    }

    private static void AppendQueryPayload(StringBuilder builder, ImmutableArray<RestApiBindablePropertyDescriptor> queryParameters)
    {
        builder.AppendLine();
        builder.AppendLine("        JsonElement? __hexalithPayload = null;");
        if (queryParameters.Length == 0)
        {
            return;
        }

        builder.AppendLine("        var __hexalithPayloadValues = new Dictionary<string, object?>(StringComparer.Ordinal)");
        builder.AppendLine("        {");
        foreach (RestApiBindablePropertyDescriptor parameter in queryParameters)
        {
            string identifier = RestApiNameSanitizer.ToIdentifier(parameter.Name, parameter.Name, camelCase: true);
            builder.Append("            [").Append(Literal(parameter.Name)).Append("] = ").Append(identifier).AppendLine(",");
        }

        builder.AppendLine("        };");
        builder.AppendLine("        __hexalithPayload = JsonSerializer.SerializeToElement(__hexalithPayloadValues, JsonOptions);");
    }

    private static void AppendQueryRouteValues(
        StringBuilder builder,
        ImmutableArray<RestApiRouteParameterDescriptor> routeParameters)
    {
        ImmutableArray<RestApiRouteParameterDescriptor> nonTenantParameters = GetNonTenantParameters(routeParameters);
        RestApiRouteParameterDescriptor? aggregateParameter = GetAggregateParameter(nonTenantParameters);
        RestApiRouteParameterDescriptor? entityParameter = GetEntityParameter(nonTenantParameters, aggregateParameter);
        string aggregateExpression = aggregateParameter.HasValue
            ? ToStringExpression(aggregateParameter.Value.Identifier, Literal("index"))
            : Literal("index");
        string entityExpression = entityParameter.HasValue
            ? ToStringExpression(entityParameter.Value.Identifier, "null")
            : "null";

        builder.AppendLine();
        builder.Append("        string __hexalithAggregateId = ").Append(aggregateExpression).AppendLine(";");
        builder.Append("        string? __hexalithEntityId = ").Append(entityExpression).AppendLine(";");
    }

    private static void AppendHttpAttribute(StringBuilder builder, RestApiRouteDescriptor route)
    {
        builder.Append("    [").Append(ToHttpAttributeName(route.Verb)).Append('(')
            .Append(Literal(route.Template)).AppendLine(")]");
    }

    private static RestApiRouteDescriptor GetRoute(RestApiMessageDescriptor message)
    {
        if (message.Route.HasValue)
        {
            return message.Route.Value;
        }

        return new RestApiRouteDescriptor(message.IsCommand ? "Post" : "Get", string.Empty);
    }

    private static ImmutableArray<RestApiRouteParameterDescriptor> GetEffectiveRouteParameters(
        RestApiOptions options,
        RestApiRouteDescriptor route)
    {
        if (route.IsAbsolute)
        {
            return route.Parameters;
        }

        ImmutableArray<RestApiRouteParameterDescriptor> prefixParameters =
            RestApiRouteTemplateParser.ParseParameters(options.RoutePrefix);
        if (prefixParameters.Length == 0)
        {
            return route.Parameters;
        }

        if (route.Parameters.Length == 0)
        {
            return prefixParameters;
        }

        return prefixParameters.AddRange(route.Parameters);
    }

    private static bool TryReserveActionMethodNames(
        RestApiMessageDescriptor message,
        HashSet<string> actionMethodNames,
        out string duplicateMethodName)
    {
        if (message.IsCommand)
        {
            string methodName = GetCommandMethodName(message);
            if (!actionMethodNames.Add(methodName))
            {
                duplicateMethodName = methodName;
                return false;
            }
        }

        if (message.IsQuery)
        {
            string methodName = GetQueryMethodName(message);
            if (!actionMethodNames.Add(methodName))
            {
                duplicateMethodName = methodName;
                return false;
            }
        }

        duplicateMethodName = string.Empty;
        return true;
    }

    private static bool TryReserveActionRoutes(
        RestApiOptions options,
        RestApiMessageDescriptor message,
        RestApiRouteDescriptor route,
        HashSet<string> actionRoutes,
        out string duplicateActionRoute)
    {
        string actionRoute = GetActionRouteKey(options, route);
        if (message.IsCommand && !actionRoutes.Add(actionRoute))
        {
            duplicateActionRoute = actionRoute;
            return false;
        }

        if (message.IsQuery && !actionRoutes.Add(actionRoute))
        {
            duplicateActionRoute = actionRoute;
            return false;
        }

        duplicateActionRoute = string.Empty;
        return true;
    }

    private static string GetCommandMethodName(RestApiMessageDescriptor message)
        => RestApiNameSanitizer.ToIdentifier(message.SimpleTypeName + "Command", "Command", camelCase: false) + "Async";

    private static string GetQueryMethodName(RestApiMessageDescriptor message)
        => RestApiNameSanitizer.ToIdentifier(message.SimpleTypeName + "Query", "Query", camelCase: false) + "Async";

    private static string GetActionRouteKey(RestApiOptions options, RestApiRouteDescriptor route)
        => route.Verb + "|" + GetEffectiveRouteTemplate(options, route);

    private static string GetEffectiveRouteTemplate(RestApiOptions options, RestApiRouteDescriptor route)
    {
        if (route.IsAbsolute)
        {
            return route.Template;
        }

        string prefix = options.RoutePrefix.TrimEnd('/');
        string template = route.Template.TrimStart('/');
        if (prefix.Length == 0)
        {
            return template;
        }

        return template.Length == 0 ? prefix : prefix + "/" + template;
    }

    private static bool TryFindDuplicateParameterIdentifier(
        RestApiMessageDescriptor message,
        ImmutableArray<RestApiRouteParameterDescriptor> routeParameters,
        out string duplicateParameter)
    {
        var identifiers = new HashSet<string>(StringComparer.Ordinal);
        foreach (string reserved in ReservedActionIdentifiers)
        {
            _ = identifiers.Add(reserved);
        }

        foreach (RestApiRouteParameterDescriptor parameter in routeParameters)
        {
            if (!identifiers.Add(parameter.Identifier))
            {
                duplicateParameter = parameter.Identifier;
                return true;
            }
        }

        if (message.IsQuery)
        {
            foreach (RestApiBindablePropertyDescriptor property in GetQueryStringProperties(message, routeParameters))
            {
                string identifier = RestApiNameSanitizer.ToIdentifier(property.Name, property.Name, camelCase: true);
                if (!identifiers.Add(identifier))
                {
                    duplicateParameter = identifier;
                    return true;
                }
            }
        }

        duplicateParameter = string.Empty;
        return false;
    }

    private static bool TryFindUnsupportedQueryParameter(
        RestApiMessageDescriptor message,
        ImmutableArray<RestApiRouteParameterDescriptor> routeParameters,
        out RestApiBindablePropertyDescriptor unsupportedProperty)
    {
        foreach (RestApiBindablePropertyDescriptor property in GetQueryStringProperties(message, routeParameters))
        {
            if (!property.CanBindFromQuery)
            {
                unsupportedProperty = property;
                return true;
            }
        }

        unsupportedProperty = default;
        return false;
    }

    private static string GetControllerName(RestApiOptions options)
    {
        string source = !string.IsNullOrWhiteSpace(options.Tag)
            ? options.Tag
            : options.RoutePrefix;
        return RestApiNameSanitizer.ToTypeName(source, "RestApi") + "RestController";
    }

    private static string GetTag(RestApiOptions options)
        => !string.IsNullOrWhiteSpace(options.Tag)
            ? options.Tag
            : RestApiNameSanitizer.ToTypeName(options.RoutePrefix, "RestApi");

    private static string ToHttpAttributeName(string verb)
    {
        switch (verb)
        {
            case "Delete":
                return "HttpDelete";
            case "Get":
                return "HttpGet";
            case "Patch":
                return "HttpPatch";
            case "Put":
                return "HttpPut";
            case "Post":
            default:
                return "HttpPost";
        }
    }

    private static ImmutableArray<RestApiRouteParameterDescriptor> GetNonTenantParameters(
        ImmutableArray<RestApiRouteParameterDescriptor> routeParameters)
        => routeParameters
            .Where(static parameter => !IsTenantParameter(parameter))
            .ToImmutableArray();

    private static RestApiRouteParameterDescriptor? GetAggregateParameter(ImmutableArray<RestApiRouteParameterDescriptor> nonTenantParameters)
    {
        foreach (RestApiRouteParameterDescriptor parameter in nonTenantParameters)
        {
            if (string.Equals(parameter.Name, "aggregateId", StringComparison.OrdinalIgnoreCase))
            {
                return parameter;
            }
        }

        return nonTenantParameters.Length == 1 ? nonTenantParameters[0] : null;
    }

    private static RestApiRouteParameterDescriptor? GetEntityParameter(
        ImmutableArray<RestApiRouteParameterDescriptor> nonTenantParameters,
        RestApiRouteParameterDescriptor? aggregateParameter)
    {
        foreach (RestApiRouteParameterDescriptor parameter in nonTenantParameters)
        {
            if (string.Equals(parameter.Name, "entityId", StringComparison.OrdinalIgnoreCase))
            {
                return parameter;
            }
        }

        foreach (RestApiRouteParameterDescriptor parameter in nonTenantParameters)
        {
            if (!aggregateParameter.HasValue || !parameter.Equals(aggregateParameter.Value))
            {
                return parameter;
            }
        }

        return null;
    }

    private static bool IsAmbiguousQueryRoute(ImmutableArray<RestApiRouteParameterDescriptor> routeParameters)
    {
        ImmutableArray<RestApiRouteParameterDescriptor> nonTenantParameters = GetNonTenantParameters(routeParameters);
        if (nonTenantParameters.Length <= 1)
        {
            return false;
        }

        bool hasAggregateId = nonTenantParameters.Any(static parameter =>
            string.Equals(parameter.Name, "aggregateId", StringComparison.OrdinalIgnoreCase));
        bool hasEntityId = nonTenantParameters.Any(static parameter =>
            string.Equals(parameter.Name, "entityId", StringComparison.OrdinalIgnoreCase));
        if (!hasAggregateId)
        {
            return true;
        }

        int extraParameters = nonTenantParameters.Length - 1 - (hasEntityId ? 1 : 0);
        return hasEntityId ? extraParameters > 0 : extraParameters > 1;
    }

    private static ImmutableArray<RestApiBindablePropertyDescriptor> GetQueryStringProperties(
        RestApiMessageDescriptor message,
        ImmutableArray<RestApiRouteParameterDescriptor> routeParameters)
        => message.Properties
            .Where(property => !routeParameters.Any(routeParameter =>
                string.Equals(routeParameter.Name, property.Name, StringComparison.OrdinalIgnoreCase)))
            .ToImmutableArray();

    private static bool TryFindProperty(
        RestApiMessageDescriptor message,
        string routeParameterName,
        out RestApiBindablePropertyDescriptor property)
    {
        foreach (RestApiBindablePropertyDescriptor candidate in message.Properties)
        {
            if (string.Equals(candidate.Name, routeParameterName, StringComparison.OrdinalIgnoreCase))
            {
                property = candidate;
                return true;
            }
        }

        property = default;
        return false;
    }

    private static string? FindRouteParameterIdentifier(
        ImmutableArray<RestApiRouteParameterDescriptor> routeParameters,
        string name)
    {
        foreach (RestApiRouteParameterDescriptor parameter in routeParameters)
        {
            if (string.Equals(parameter.Name, name, StringComparison.OrdinalIgnoreCase))
            {
                return parameter.Identifier;
            }
        }

        return null;
    }

    private static bool HasTenantRouteParameter(ImmutableArray<RestApiRouteParameterDescriptor> routeParameters)
        => routeParameters.Any(static parameter => IsTenantParameter(parameter));

    private static bool IsTenantParameter(RestApiRouteParameterDescriptor parameter)
        => string.Equals(parameter.Name, "tenant", StringComparison.OrdinalIgnoreCase)
            || string.Equals(parameter.Name, "tenantId", StringComparison.OrdinalIgnoreCase);

    private static bool RequiresRouteTenant(RestApiOptions options)
        => string.Equals(options.TenantSource, "Route", StringComparison.Ordinal);

    private static string ToStringExpression(string identifier, string fallbackExpression)
        => "Convert.ToString(" + identifier + ", CultureInfo.InvariantCulture) ?? " + fallbackExpression;

    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, quote: true);
}
