using System.Collections.Immutable;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Hexalith.EventStore.RestApi.Generators;

internal static class RestApiManifestEmitter
{
    public const string HintName = "HexalithEventStoreRestApiGeneratorManifest.g.cs";

    public static string Emit(RestApiOptions options, ImmutableArray<RestApiMessageDescriptor> messages)
    {
        ImmutableArray<string> commandTypes = messages
            .Where(static message => message.IsCommand)
            .Select(static message => message.TypeName)
            .OrderBy(static typeName => typeName, StringComparer.Ordinal)
            .ToImmutableArray();
        ImmutableArray<string> queryTypes = messages
            .Where(static message => message.IsQuery)
            .Select(static message => message.TypeName)
            .OrderBy(static typeName => typeName, StringComparer.Ordinal)
            .ToImmutableArray();
        ImmutableArray<string> routeOverrides = messages
            .Where(static message => message.Route.HasValue)
            .Select(static message => FormatRouteOverride(message))
            .OrderBy(static route => route, StringComparer.Ordinal)
            .ToImmutableArray();

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace Hexalith.EventStore.RestApi.Generated;");
        builder.AppendLine();
        builder.AppendLine("internal static class RestApiGeneratorManifest");
        builder.AppendLine("{");
        builder.AppendLine("    internal const bool RestApiAttributeFound = true;");
        builder.Append("    internal const string RoutePrefix = ").Append(Literal(options.RoutePrefix)).AppendLine(";");
        builder.Append("    internal const string Tag = ").Append(Literal(options.Tag)).AppendLine(";");
        builder.Append("    internal const string TenantSource = ").Append(Literal(options.TenantSource)).AppendLine(";");
        builder.Append("    internal const int CommandCount = ").Append(commandTypes.Length).AppendLine(";");
        builder.Append("    internal const int QueryCount = ").Append(queryTypes.Length).AppendLine(";");
        builder.Append("    internal const int RouteOverrideCount = ").Append(routeOverrides.Length).AppendLine(";");
        builder.AppendLine();
        AppendArray(builder, "CommandTypes", commandTypes);
        builder.AppendLine();
        AppendArray(builder, "QueryTypes", queryTypes);
        builder.AppendLine();
        AppendArray(builder, "RouteOverrides", routeOverrides);
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static string FormatRouteOverride(RestApiMessageDescriptor message)
    {
        RestApiRouteDescriptor route = message.Route!.Value;
        return message.TypeName + "|" + route.Verb + "|" + route.Template;
    }

    private static void AppendArray(StringBuilder builder, string name, ImmutableArray<string> values)
    {
        builder.Append("    internal static string[] ").Append(name).AppendLine(" { get; } = new string[]");
        builder.AppendLine("    {");

        foreach (string value in values)
        {
            builder.Append("        ").Append(Literal(value)).AppendLine(",");
        }

        builder.AppendLine("    };");
    }

    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, quote: true);
}
