using System.Reflection;
using System.Text.Json;
using Hexalith.EventStore.Client.Handlers;
using Hexalith.EventStore.Contracts.Events;
var metadata = new EventMetadata("message", "aggregate", "mutation", "tenant", "domain", 1, 1, DateTimeOffset.UnixEpoch, "correlation", "cause", "user", "1", "Event", 1, "json");
string json=JsonSerializer.Serialize(metadata,new JsonSerializerOptions(JsonSerializerDefaults.Web));
json=json[..^1]+",\""+new string('x',400000)+"\":0}";
string outer="{\"currentSequence\":1,\"events\":[{\"metadata\":"+json+",\"payload\":\"e30=\",\"extensions\":{}}]}";
using var source=JsonDocument.Parse(outer);
using var owner=new LegacyCommandReplayInput(default);
long start=GC.GetAllocatedBytesForCurrentThread();
_=owner.CaptureJson(source.RootElement,true);
long allocations=GC.GetAllocatedBytesForCurrentThread()-start;
long accounted=(long)typeof(LegacyCommandReplayInput).GetField("_accountedBytes",BindingFlags.Instance|BindingFlags.NonPublic)!.GetValue(owner)!;
Console.WriteLine($"unknown_name=400000; admitted_charge={accounted}; capture_allocations={allocations}");
