using System.Text;

namespace Hexalith.EventStore.Admin.Cli.Commands.Config;

/// <summary>
/// Generates shell completion scripts for various shells.
/// </summary>
public static class CompletionScripts {
    private const string Subcommands = "health stream projection tenant snapshot backup config";
    private const string GlobalOptions = "--url --token --format --output --profile";
    private const string FormatValues = "json csv table";
    private const string ConfigSubcommands = "profile use current completion";
    private const string ProfileSubcommands = "add list show remove";

    /// <summary>
    /// Generates a bash completion script.
    /// </summary>
    public static string GenerateBash() {
        StringBuilder sb = new();
        _ = sb.AppendLine($"# Generated by eventstore-admin config completion bash on {DateTime.UtcNow:yyyy-MM-dd}");
        _ = sb.AppendLine("# Add to ~/.bashrc: eval \"$(eventstore-admin config completion bash)\"");
        _ = sb.AppendLine();
        _ = sb.AppendLine("_eventstore_admin_completions() {");
        _ = sb.AppendLine("    local cur prev words cword");
        _ = sb.AppendLine("    _init_completion || return");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    # Dynamic profile names");
        _ = sb.AppendLine("    local profiles=\"\"");
        _ = sb.AppendLine("    local profile_file=\"${HOME}/.eventstore/profiles.json\"");
        _ = sb.AppendLine("    if [ -f \"${profile_file}\" ]; then");
        _ = sb.AppendLine("        profiles=$(grep -o '\"[a-zA-Z0-9_-]*\"\\s*:' \"${profile_file}\" | sed 's/[\":]//g; s/^\\s*//; s/\\s*$//' | grep -v '^version$\\|^activeProfile$\\|^profiles$\\|^url$\\|^token$\\|^format$')");
        _ = sb.AppendLine("    fi");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    case \"${prev}\" in");
        _ = sb.AppendLine("        --format|-f)");
        _ = sb.AppendLine($"            COMPREPLY=( $(compgen -W \"{FormatValues}\" -- \"${{cur}}\") )");
        _ = sb.AppendLine("            return;;");
        _ = sb.AppendLine("        --profile|-p)");
        _ = sb.AppendLine("            COMPREPLY=( $(compgen -W \"${profiles}\" -- \"${cur}\") )");
        _ = sb.AppendLine("            return;;");
        _ = sb.AppendLine("        --output|-o|--url|-u|--token|-t)");
        _ = sb.AppendLine("            return;;");
        _ = sb.AppendLine("    esac");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    local subcmd=\"\"");
        _ = sb.AppendLine("    for ((i=1; i < cword; i++)); do");
        _ = sb.AppendLine("        case \"${words[i]}\" in");
        _ = sb.AppendLine("            -*);;");
        _ = sb.AppendLine("            *) subcmd=\"${subcmd:+${subcmd} }${words[i]}\";;");
        _ = sb.AppendLine("        esac");
        _ = sb.AppendLine("    done");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    case \"${subcmd}\" in");
        _ = sb.AppendLine("        \"\")");
        _ = sb.AppendLine($"            COMPREPLY=( $(compgen -W \"{Subcommands} {GlobalOptions}\" -- \"${{cur}}\") );;");
        _ = sb.AppendLine("        config)");
        _ = sb.AppendLine($"            COMPREPLY=( $(compgen -W \"{ConfigSubcommands}\" -- \"${{cur}}\") );;");
        _ = sb.AppendLine("        \"config profile\")");
        _ = sb.AppendLine($"            COMPREPLY=( $(compgen -W \"{ProfileSubcommands}\" -- \"${{cur}}\") );;");
        _ = sb.AppendLine("        \"config use\")");
        _ = sb.AppendLine("            COMPREPLY=( $(compgen -W \"${profiles} --clear\" -- \"${cur}\") );;");
        _ = sb.AppendLine("        \"config completion\")");
        _ = sb.AppendLine("            COMPREPLY=( $(compgen -W \"bash zsh powershell fish\" -- \"${cur}\") );;");
        _ = sb.AppendLine("        health)");
        _ = sb.AppendLine("            COMPREPLY=( $(compgen -W \"dapr --wait --interval --strict\" -- \"${cur}\") );;");
        _ = sb.AppendLine("        stream)");
        _ = sb.AppendLine("            COMPREPLY=( $(compgen -W \"list events event state diff causation\" -- \"${cur}\") );;");
        _ = sb.AppendLine("        projection)");
        _ = sb.AppendLine("            COMPREPLY=( $(compgen -W \"list status pause resume reset\" -- \"${cur}\") );;");
        _ = sb.AppendLine("        tenant)");
        _ = sb.AppendLine("            COMPREPLY=( $(compgen -W \"list detail quotas users compare verify\" -- \"${cur}\") );;");
        _ = sb.AppendLine("        snapshot)");
        _ = sb.AppendLine("            COMPREPLY=( $(compgen -W \"create policies set-policy delete-policy\" -- \"${cur}\") );;");
        _ = sb.AppendLine("        backup)");
        _ = sb.AppendLine("            COMPREPLY=( $(compgen -W \"list trigger restore validate export-stream import-stream\" -- \"${cur}\") );;");
        _ = sb.AppendLine("    esac");
        _ = sb.AppendLine("}");
        _ = sb.AppendLine();
        _ = sb.AppendLine("complete -F _eventstore_admin_completions eventstore-admin");
        return sb.ToString();
    }

    /// <summary>
    /// Generates a zsh completion script.
    /// </summary>
    public static string GenerateZsh() {
        StringBuilder sb = new();
        _ = sb.AppendLine($"# Generated by eventstore-admin config completion zsh on {DateTime.UtcNow:yyyy-MM-dd}");
        _ = sb.AppendLine("# Add to ~/.zshrc: eval \"$(eventstore-admin config completion zsh)\"");
        _ = sb.AppendLine();
        _ = sb.AppendLine("_eventstore_admin() {");
        _ = sb.AppendLine("    local -a subcommands profiles");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    # Dynamic profile names");
        _ = sb.AppendLine("    _eventstore_profiles() {");
        _ = sb.AppendLine("        local profile_file=\"${HOME}/.eventstore/profiles.json\"");
        _ = sb.AppendLine("        if [ -f \"${profile_file}\" ]; then");
        _ = sb.AppendLine("            profiles=($(grep -o '\"[a-zA-Z0-9_-]*\"\\s*:' \"${profile_file}\" | sed 's/[\":]//g; s/^\\s*//; s/\\s*$//' | grep -v '^version$\\|^activeProfile$\\|^profiles$\\|^url$\\|^token$\\|^format$'))");
        _ = sb.AppendLine("        fi");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    _arguments -s \\");
        _ = sb.AppendLine("        '--url[Admin API base URL]:url:' \\");
        _ = sb.AppendLine("        '--token[JWT Bearer token or API key]:token:' \\");
        _ = sb.AppendLine("        '--format[Output format]:format:(json csv table)' \\");
        _ = sb.AppendLine("        '--output[Redirect output to file]:file:_files' \\");
        _ = sb.AppendLine("        '--profile[Connection profile name]:profile:{_eventstore_profiles; compadd -a profiles}' \\");
        _ = sb.AppendLine("        '1:command:(health stream projection tenant snapshot backup config)' \\");
        _ = sb.AppendLine("        '*::arg:->args'");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    case $state in");
        _ = sb.AppendLine("        args)");
        _ = sb.AppendLine("            case ${words[1]} in");
        _ = sb.AppendLine("                config) compadd profile use current completion;;");
        _ = sb.AppendLine("                health) compadd dapr;;");
        _ = sb.AppendLine("                stream) compadd list events event state diff causation;;");
        _ = sb.AppendLine("                projection) compadd list status pause resume reset;;");
        _ = sb.AppendLine("                tenant) compadd list detail quotas users compare verify;;");
        _ = sb.AppendLine("                snapshot) compadd create policies set-policy delete-policy;;");
        _ = sb.AppendLine("                backup) compadd list trigger restore validate export-stream import-stream;;");
        _ = sb.AppendLine("            esac");
        _ = sb.AppendLine("            ;;");
        _ = sb.AppendLine("    esac");
        _ = sb.AppendLine("}");
        _ = sb.AppendLine();
        _ = sb.AppendLine("compdef _eventstore_admin eventstore-admin");
        return sb.ToString();
    }

    /// <summary>
    /// Generates a PowerShell completion script.
    /// </summary>
    public static string GeneratePowerShell() {
        StringBuilder sb = new();
        _ = sb.AppendLine($"# Generated by eventstore-admin config completion powershell on {DateTime.UtcNow:yyyy-MM-dd}");
        _ = sb.AppendLine("# Add to $PROFILE: Invoke-Expression (eventstore-admin config completion powershell | Out-String)");
        _ = sb.AppendLine();
        _ = sb.AppendLine("Register-ArgumentCompleter -CommandName eventstore-admin -ScriptBlock {");
        _ = sb.AppendLine("    param($wordToComplete, $commandAst, $cursorPosition)");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    $commands = $commandAst.CommandElements | ForEach-Object { $_.ToString() }");
        _ = sb.AppendLine("    $subcommands = $commands | Select-Object -Skip 1 | Where-Object { $_ -notmatch '^-' }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    # Dynamic profile names");
        _ = sb.AppendLine("    function Get-Profiles {");
        _ = sb.AppendLine("        $profileFile = Join-Path $env:USERPROFILE '.eventstore' 'profiles.json'");
        _ = sb.AppendLine("        if (Test-Path $profileFile) {");
        _ = sb.AppendLine("            $json = Get-Content $profileFile | ConvertFrom-Json");
        _ = sb.AppendLine("            if ($json.profiles) {");
        _ = sb.AppendLine("                $json.profiles | Get-Member -MemberType NoteProperty | Select-Object -ExpandProperty Name");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    # Check if previous word is an option that expects a value");
        _ = sb.AppendLine("    $prevWord = if ($commands.Count -gt 1) { $commands[-2] } else { '' }");
        _ = sb.AppendLine("    switch ($prevWord) {");
        _ = sb.AppendLine("        { $_ -in '--format', '-f' } {");
        _ = sb.AppendLine("            'json', 'csv', 'table' | Where-Object { $_ -like \"$wordToComplete*\" } |");
        _ = sb.AppendLine("                ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }");
        _ = sb.AppendLine("            return");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("        { $_ -in '--profile', '-p' } {");
        _ = sb.AppendLine("            Get-Profiles | Where-Object { $_ -like \"$wordToComplete*\" } |");
        _ = sb.AppendLine("                ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }");
        _ = sb.AppendLine("            return");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    $completions = switch ($subcommands -join ' ') {");
        _ = sb.AppendLine($"        '' {{ '{Subcommands}'.Split() }}");
        _ = sb.AppendLine($"        'config' {{ '{ConfigSubcommands}'.Split() }}");
        _ = sb.AppendLine($"        'config profile' {{ '{ProfileSubcommands}'.Split() }}");
        _ = sb.AppendLine("        'config use' { @((Get-Profiles) + '--clear') }");
        _ = sb.AppendLine("        'config completion' { 'bash', 'zsh', 'powershell', 'fish' }");
        _ = sb.AppendLine("        'health' { 'dapr' }");
        _ = sb.AppendLine("        'stream' { 'list', 'events', 'event', 'state', 'diff', 'causation' }");
        _ = sb.AppendLine("        'projection' { 'list', 'status', 'pause', 'resume', 'reset' }");
        _ = sb.AppendLine("        'tenant' { 'list', 'detail', 'quotas', 'users', 'compare', 'verify' }");
        _ = sb.AppendLine("        'snapshot' { 'create', 'policies', 'set-policy', 'delete-policy' }");
        _ = sb.AppendLine("        'backup' { 'list', 'trigger', 'restore', 'validate', 'export-stream', 'import-stream' }");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    $completions | Where-Object { $_ -like \"$wordToComplete*\" } |");
        _ = sb.AppendLine("        ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }");
        _ = sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Generates a fish completion script.
    /// </summary>
    public static string GenerateFish() {
        StringBuilder sb = new();
        _ = sb.AppendLine($"# Generated by eventstore-admin config completion fish on {DateTime.UtcNow:yyyy-MM-dd}");
        _ = sb.AppendLine("# Add to ~/.config/fish/completions/eventstore-admin.fish or eval:");
        _ = sb.AppendLine("# eventstore-admin config completion fish | source");
        _ = sb.AppendLine();
        _ = sb.AppendLine("# Dynamic profile names");
        _ = sb.AppendLine("function __eventstore_profiles");
        _ = sb.AppendLine("    set -l profile_file \"$HOME/.eventstore/profiles.json\"");
        _ = sb.AppendLine("    if test -f \"$profile_file\"");
        _ = sb.AppendLine("        grep -o '\"[a-zA-Z0-9_-]*\"\\s*:' \"$profile_file\" | sed 's/[\":]//g; s/^\\s*//; s/\\s*//' | grep -v '^version$\\|^activeProfile$\\|^profiles$\\|^url$\\|^token$\\|^format$'");
        _ = sb.AppendLine("    end");
        _ = sb.AppendLine("end");
        _ = sb.AppendLine();
        _ = sb.AppendLine("# Global options");
        _ = sb.AppendLine("complete -c eventstore-admin -l url -s u -d 'Admin API base URL'");
        _ = sb.AppendLine("complete -c eventstore-admin -l token -s t -d 'JWT Bearer token or API key'");
        _ = sb.AppendLine("complete -c eventstore-admin -l format -s f -d 'Output format' -xa 'json csv table'");
        _ = sb.AppendLine("complete -c eventstore-admin -l output -s o -d 'Redirect output to file' -rF");
        _ = sb.AppendLine("complete -c eventstore-admin -l profile -s p -d 'Connection profile name' -xa '(__eventstore_profiles)'");
        _ = sb.AppendLine();
        _ = sb.AppendLine("# Top-level subcommands");
        _ = sb.AppendLine("complete -c eventstore-admin -n '__fish_use_subcommand' -a health -d 'Check server health'");
        _ = sb.AppendLine("complete -c eventstore-admin -n '__fish_use_subcommand' -a stream -d 'Manage event streams'");
        _ = sb.AppendLine("complete -c eventstore-admin -n '__fish_use_subcommand' -a projection -d 'Manage projections'");
        _ = sb.AppendLine("complete -c eventstore-admin -n '__fish_use_subcommand' -a tenant -d 'Manage tenants'");
        _ = sb.AppendLine("complete -c eventstore-admin -n '__fish_use_subcommand' -a snapshot -d 'Manage snapshots'");
        _ = sb.AppendLine("complete -c eventstore-admin -n '__fish_use_subcommand' -a backup -d 'Manage backups'");
        _ = sb.AppendLine("complete -c eventstore-admin -n '__fish_use_subcommand' -a config -d 'Manage connection profiles and CLI configuration'");
        _ = sb.AppendLine();
        _ = sb.AppendLine("# Config subcommands");
        _ = sb.AppendLine("complete -c eventstore-admin -n '__fish_seen_subcommand_from config; and not __fish_seen_subcommand_from profile use current completion' -a profile -d 'Manage profiles'");
        _ = sb.AppendLine("complete -c eventstore-admin -n '__fish_seen_subcommand_from config; and not __fish_seen_subcommand_from profile use current completion' -a use -d 'Set active profile'");
        _ = sb.AppendLine("complete -c eventstore-admin -n '__fish_seen_subcommand_from config; and not __fish_seen_subcommand_from profile use current completion' -a current -d 'Show resolved settings'");
        _ = sb.AppendLine("complete -c eventstore-admin -n '__fish_seen_subcommand_from config; and not __fish_seen_subcommand_from profile use current completion' -a completion -d 'Generate completion scripts'");
        _ = sb.AppendLine();
        _ = sb.AppendLine("# Profile subcommands");
        _ = sb.AppendLine("complete -c eventstore-admin -n '__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from add list show remove' -a add -d 'Create or update a profile'");
        _ = sb.AppendLine("complete -c eventstore-admin -n '__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from add list show remove' -a list -d 'List all profiles'");
        _ = sb.AppendLine("complete -c eventstore-admin -n '__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from add list show remove' -a show -d 'Show profile details'");
        _ = sb.AppendLine("complete -c eventstore-admin -n '__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from add list show remove' -a remove -d 'Remove a profile'");
        _ = sb.AppendLine();
        _ = sb.AppendLine("# Config use dynamic profile completions");
        _ = sb.AppendLine("complete -c eventstore-admin -n '__fish_seen_subcommand_from config; and __fish_seen_subcommand_from use' -xa '(__eventstore_profiles)' -d 'Profile name'");
        _ = sb.AppendLine("complete -c eventstore-admin -n '__fish_seen_subcommand_from config; and __fish_seen_subcommand_from use' -l clear -d 'Clear active profile'");
        _ = sb.AppendLine();
        _ = sb.AppendLine("# Config completion shell types");
        _ = sb.AppendLine("complete -c eventstore-admin -n '__fish_seen_subcommand_from completion' -xa 'bash zsh powershell fish' -d 'Shell type'");
        _ = sb.AppendLine();
        _ = sb.AppendLine("# Stream subcommands");
        _ = sb.AppendLine("complete -c eventstore-admin -n '__fish_seen_subcommand_from stream; and not __fish_seen_subcommand_from list events event state diff causation' -a 'list events event state diff causation'");
        _ = sb.AppendLine();
        _ = sb.AppendLine("# Projection subcommands");
        _ = sb.AppendLine("complete -c eventstore-admin -n '__fish_seen_subcommand_from projection; and not __fish_seen_subcommand_from list status pause resume reset' -a 'list status pause resume reset'");
        _ = sb.AppendLine();
        _ = sb.AppendLine("# Tenant subcommands");
        _ = sb.AppendLine("complete -c eventstore-admin -n '__fish_seen_subcommand_from tenant; and not __fish_seen_subcommand_from list detail quotas users compare verify' -a 'list detail quotas users compare verify'");
        _ = sb.AppendLine();
        _ = sb.AppendLine("# Snapshot subcommands");
        _ = sb.AppendLine("complete -c eventstore-admin -n '__fish_seen_subcommand_from snapshot; and not __fish_seen_subcommand_from create policies set-policy delete-policy' -a 'create policies set-policy delete-policy'");
        _ = sb.AppendLine();
        _ = sb.AppendLine("# Backup subcommands");
        _ = sb.AppendLine("complete -c eventstore-admin -n '__fish_seen_subcommand_from backup; and not __fish_seen_subcommand_from list trigger restore validate export-stream import-stream' -a 'list trigger restore validate export-stream import-stream'");
        return sb.ToString();
    }
}
