<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EventStoreVersion Condition="'$(EventStoreVersion)' == ''">3.110.0</EventStoreVersion>
    <UseCurrentSource Condition="'$(UseCurrentSource)' == ''">false</UseCurrentSource>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
</Project>
