using System.Text.Json;
using System.Text.Json.Serialization;
using Hexalith.EventStore.Client.Aggregates;
using Hexalith.EventStore.Contracts.Commands;
using Hexalith.EventStore.Contracts.Events;
using Hexalith.EventStore.Contracts.Replay;
using Hexalith.EventStore.Contracts.Security;
using Hexalith.EventStore.Server.Events;
using Hexalith.EventStore.Contracts.Identity;
using CEvent = Hexalith.EventStore.Contracts.Events.EventEnvelope;
var aggregate = new Aggregate();
var command = new CommandEnvelope("m", "tenant", "domain", "id", nameof(Evt), "{}"u8.ToArray(), "c", null, "u", null);
CEvent Event(long seq, string type = nameof(Evt)) => new(new EventMetadata("m", "id", "aggregate", "tenant", "domain", seq, seq, DateTimeOffset.UnixEpoch, "c", "c", "u", "v1", type, 1, "json"), "{}"u8.ToArray(), null);
var extra = new CEvent(Event(1).Metadata with { EventContractType = "versioned-event", PayloadVersion = 2 }, "{}"u8.ToArray(), null);
State.Applied=0;
await aggregate.ProcessAsync(command, new DomainServiceCurrentState(null, [extra], 0, 1));
Console.WriteLine($"version fields: applies={State.Applied}");
var protectedExtra = new CEvent(Event(1).Metadata, "{}"u8.ToArray(), EventStorePayloadProtectionMetadataCarrier.Write((IReadOnlyDictionary<string,string>?)null, new EventStorePayloadProtectionMetadata(PayloadProtectionState.Protected, 1, "scheme", "alias", null, null)));
State.Applied=0;
await aggregate.ProcessAsync(command, new DomainServiceCurrentState(null, [protectedExtra], 0, 1));
Console.WriteLine($"protected metadata with json: applies={State.Applied}");
State.Applied=0;
await aggregate.ProcessAsync(command, new object?[] { Event(1), null, Event(2) });
Console.WriteLine($"null enumerable event: applies={State.Applied}");
State.Applied=0;
await aggregate.ProcessAsync(command, new DomainServiceCurrentState(null, [Event(1), Event(3)], 0, 3));
Console.WriteLine($"gapped stream: applies={State.Applied}");
State.Applied=0;
await aggregate.ProcessAsync(command, new DomainServiceCurrentState(null, [Event(1)], 0, 20));
Console.WriteLine($"head mismatch: applies={State.Applied}");
State.Applied=0;
var crossTenant = new CEvent(Event(1).Metadata with { TenantId = "other-tenant", AggregateId = "other-aggregate" }, "{}"u8.ToArray(), null);
await aggregate.ProcessAsync(command, new DomainServiceCurrentState(null, [crossTenant], 0, 1));
Console.WriteLine($"cross-identity event: applies={State.Applied}");
var mutable = new[] { Event(1), Event(2, "Unknown") };
Convert.OnRead = () => mutable[1] = Event(2);
State.Applied=0;
await aggregate.ProcessAsync(command, new DomainServiceCurrentState(null, mutable, 0, 2));
Console.WriteLine($"converter replaces unknown: applies={State.Applied}");
Convert.OnRead=null;
var request = new AggregateReconstructionRequest("tenant", "domain", "aggregate", "id", -1, [new ReplayEventEnvelope(1,nameof(Evt),"{}"u8.ToArray(),"json",1,"m",null,null)],false,null);
Console.WriteLine($"negative target status={AggregateReplayer.Replay<State>(request).Status}");
var protector = new NoOpEventPayloadProtectionService();
var jsonSnapshot = JsonDocument.Parse("{\"format\":\"json\",\"Format\":\"json+pdenc-v2\",\"snapshotTypeId\":\"counter\",\"envelope\":\"abc\"}").RootElement;
Console.WriteLine($"mixed-case protected snapshot readable={(await protector.TryUnprotectSnapshotAsync(new AggregateIdentity("tenant","domain","id"),jsonSnapshot,null)).IsReadable}");
var dictSnapshot = new Dictionary<string,object> { ["format"]="json+pdenc-v2", ["snapshotTypeId"]="counter", ["envelope"]="abc" };
Console.WriteLine($"dictionary protected snapshot readable={(await protector.TryUnprotectSnapshotAsync(new AggregateIdentity("tenant","domain","id"),dictSnapshot,null)).IsReadable}");
public class Aggregate : EventStoreAggregate<State> { public Hexalith.EventStore.Contracts.Results.DomainResult Handle(Evt evt, State? state) => Hexalith.EventStore.Contracts.Results.DomainResult.NoOp(); }
public class State { public static int Applied; public void Apply(Evt evt) => Applied++; }
[JsonConverter(typeof(Convert))] public class Evt : IEventPayload;
public class Convert : JsonConverter<Evt> { public static Action? OnRead; public override Evt Read(ref Utf8JsonReader reader, Type type, JsonSerializerOptions options) { using var doc=JsonDocument.ParseValue(ref reader); OnRead?.Invoke(); return new(); } public override void Write(Utf8JsonWriter writer, Evt value, JsonSerializerOptions options) { writer.WriteStartObject(); writer.WriteEndObject(); } }
