using System.Text;

using Hexalith.EventStore.Client.Registration;
using Hexalith.EventStore.Sample.Api.Services;
using Hexalith.EventStore.ServiceDefaults;

using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.IdentityModel.Tokens;

WebApplicationBuilder builder = WebApplication.CreateBuilder(args);

builder.AddServiceDefaults();

// The typed REST controllers are generated by the Hexalith.EventStore.RestApi.Generators analyzer from
// the [RestRoute]-annotated contracts in Hexalith.EventStore.Sample.Contracts, discovered via
// referenced-assembly metadata. This host is the external-facing REST surface for third-party
// applications; the interactive Blazor UI host consumes the platform gateway client instead.
builder.Services.AddControllers();
builder.Services.AddHttpContextAccessor();

// Inbound JWT validation for the generated [Authorize] controllers — external callers present a bearer.
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options => {
        options.MapInboundClaims = false;
        options.TokenValidationParameters = new TokenValidationParameters {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateIssuerSigningKey = true,
            ValidateLifetime = true,
            ClockSkew = TimeSpan.FromMinutes(1),
            ValidIssuer = builder.Configuration["EventStore:Authentication:Issuer"] ?? "hexalith-dev",
            ValidAudience = builder.Configuration["EventStore:Authentication:Audience"] ?? "hexalith-eventstore",
        };

        string? authority = builder.Configuration["EventStore:Authentication:Authority"];
        if (!string.IsNullOrWhiteSpace(authority)) {
            options.Authority = authority;
            options.RequireHttpsMetadata = builder.Configuration.GetValue("EventStore:Authentication:RequireHttpsMetadata", true);
        }
        else {
            string signingKey = builder.Configuration["EventStore:Authentication:SigningKey"]
                ?? throw new InvalidOperationException("EventStore:Authentication:SigningKey is required when Authority is not configured.");
            options.TokenValidationParameters.IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(signingKey));
        }
    });
builder.Services.AddAuthorization();

// Outbound path to the EventStore gateway via this app's DAPR sidecar. The caller's validated bearer is
// forwarded unchanged so EventStore's JWT/RBAC/tenant enforcement stays authoritative. A literal
// localhost base address keeps the global AddServiceDiscovery() default a no-op.
string daprHttpEndpoint = builder.Configuration["DAPR_HTTP_ENDPOINT"]
    ?? $"http://localhost:{builder.Configuration["DAPR_HTTP_PORT"] ?? "3500"}";
string? daprApiToken = builder.Configuration["DAPR_API_TOKEN"];

builder.Services.AddTransient<InboundBearerForwardingHandler>();
builder.Services.AddEventStoreGatewayClient(options => options.BaseAddress = new Uri(daprHttpEndpoint))
    .AddHttpMessageHandler<InboundBearerForwardingHandler>()
    .AddHttpMessageHandler(() => new DaprAppIdHandler("eventstore", daprApiToken));

WebApplication app = builder.Build();

if (!app.Environment.IsDevelopment()) {
    _ = app.UseHsts();
}

app.UseHttpsRedirection();
app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();
app.MapDefaultEndpoints();

app.Run();
