using Hexalith.EventStore.Client.Registration;
using Hexalith.EventStore.Sample.Api.Services;
using Hexalith.EventStore.ServiceDefaults;
using Hexalith.EventStore.ServiceDefaults.Authentication;

using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.Extensions.Options;

WebApplicationBuilder builder = WebApplication.CreateBuilder(args);

builder.AddServiceDefaults();

// The typed REST controllers are generated by the Hexalith.EventStore.RestApi.Generators analyzer from
// the [RestRoute]-annotated contracts in Hexalith.EventStore.Sample.Contracts, discovered via
// referenced-assembly metadata. This host is the external-facing REST surface for third-party
// applications; the interactive Blazor UI host consumes the platform gateway client instead.
builder.Services.AddControllers();
builder.Services.AddHttpContextAccessor();

// Inbound JWT validation for the generated [Authorize] controllers — external callers present a bearer.
builder.Services
    .AddOptions<JwtBearerAuthenticationOptions>()
    .BindConfiguration("Authentication:JwtBearer")
    .ValidateOnStart();
builder.Services.AddSingleton<IValidateOptions<JwtBearerAuthenticationOptions>, ValidateJwtBearerAuthenticationOptions>();
builder.Services.AddSingleton<IConfigureOptions<JwtBearerOptions>, ConfigureJwtBearerAuthenticationOptions>();
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer();
builder.Services.AddAuthorization();

// Outbound path to the EventStore gateway via this app's DAPR sidecar. The caller's validated bearer is
// forwarded unchanged so EventStore's JWT/RBAC/tenant enforcement stays authoritative. A literal
// localhost base address keeps the global AddServiceDiscovery() default a no-op.
string daprHttpEndpoint = DaprHttpEndpointResolver.Resolve(builder.Configuration);
string? daprApiToken = builder.Configuration["DAPR_API_TOKEN"];

builder.Services.AddTransient<InboundBearerForwardingHandler>();
builder.Services.AddEventStoreGatewayClient(options => options.BaseAddress = new Uri(daprHttpEndpoint))
    .AddHttpMessageHandler<InboundBearerForwardingHandler>()
    .AddEventStoreDaprServiceInvocation("eventstore", daprApiToken);

// AD-17: opt into the absolute command-status Location header when a browser-facing gateway origin is
// configured. When the value is absent or malformed the AddEventStoreGatewayClient fail-closed default
// applies (generated command 202 responses emit no Location header).
// The guard mirrors AddEventStoreCommandStatusLocation's own validation (absolute http(s) origin, no user
// info / query / fragment) so a malformed config value is skipped (fail-closed default applies) rather than
// throwing inside the extension and crashing host startup.
string? gatewayStatusBase = builder.Configuration["EventStore:GatewayStatusBase"]?.Trim();
if (!string.IsNullOrWhiteSpace(gatewayStatusBase)
    && Uri.TryCreate(gatewayStatusBase, UriKind.Absolute, out Uri? gatewayStatusBaseUri)
    && (gatewayStatusBaseUri.Scheme == Uri.UriSchemeHttp || gatewayStatusBaseUri.Scheme == Uri.UriSchemeHttps)
    && string.IsNullOrEmpty(gatewayStatusBaseUri.UserInfo)
    && string.IsNullOrEmpty(gatewayStatusBaseUri.Query)
    && string.IsNullOrEmpty(gatewayStatusBaseUri.Fragment)) {
    builder.Services.AddEventStoreCommandStatusLocation(gatewayStatusBaseUri);
}

WebApplication app = builder.Build();

if (!app.Environment.IsDevelopment()) {
    _ = app.UseHsts();
}

app.UseHttpsRedirection();
app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();
app.MapDefaultEndpoints();

app.Run();

/// <summary>
/// Entry point class, made partial for WebApplicationFactory test access.
/// </summary>
public partial class Program;
