using System.Text;

using Hexalith.EventStore.Client.Registration;
using Hexalith.EventStore.Sample.Api.Services;
using Hexalith.EventStore.ServiceDefaults;

using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.IdentityModel.Tokens;

WebApplicationBuilder builder = WebApplication.CreateBuilder(args);

builder.AddServiceDefaults();

// The typed REST controllers are generated by the Hexalith.EventStore.RestApi.Generators analyzer from
// the [RestRoute]-annotated contracts in Hexalith.EventStore.Sample.Contracts, discovered via
// referenced-assembly metadata. This host is the external-facing REST surface for third-party
// applications; the interactive Blazor UI host consumes the platform gateway client instead.
builder.Services.AddControllers();
builder.Services.AddHttpContextAccessor();

// Inbound JWT validation for the generated [Authorize] controllers — external callers present a bearer.
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options => {
        options.MapInboundClaims = false;

        string? issuer = builder.Configuration["EventStore:Authentication:Issuer"];
        string? audience = builder.Configuration["EventStore:Authentication:Audience"];

        options.TokenValidationParameters = new TokenValidationParameters {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateIssuerSigningKey = true,
            ValidateLifetime = true,
            ClockSkew = TimeSpan.FromMinutes(1),
            ValidAudience = string.IsNullOrWhiteSpace(audience) ? "hexalith-eventstore" : audience,
        };

        string? authority = builder.Configuration["EventStore:Authentication:Authority"];
        if (!string.IsNullOrWhiteSpace(authority)) {
            // Authority (OIDC/Keycloak) mode: the discovered metadata issuer drives issuer validation.
            // Only pin ValidIssuer when explicitly configured -- never fall back to the dev issuer here,
            // otherwise a real realm-URL issuer is rejected while "hexalith-dev" stays permanently trusted.
            options.Authority = authority;
            options.RequireHttpsMetadata = builder.Configuration.GetValue("EventStore:Authentication:RequireHttpsMetadata", true);
            if (!string.IsNullOrWhiteSpace(issuer)) {
                options.TokenValidationParameters.ValidIssuer = issuer;
            }
        }
        else {
            // Symmetric-key dev mode (EnableKeycloak=false): keep the dev issuer default so local tokens validate.
            options.TokenValidationParameters.ValidIssuer = string.IsNullOrWhiteSpace(issuer) ? "hexalith-dev" : issuer;

            string? signingKey = builder.Configuration["EventStore:Authentication:SigningKey"];
            if (string.IsNullOrWhiteSpace(signingKey)) {
                throw new InvalidOperationException("EventStore:Authentication:SigningKey is required when Authority is not configured.");
            }

            if (Encoding.UTF8.GetByteCount(signingKey) < 32) {
                throw new InvalidOperationException("EventStore:Authentication:SigningKey must be at least 32 bytes (256 bits) for HS256 token validation.");
            }

            options.TokenValidationParameters.IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(signingKey));
        }
    });
builder.Services.AddAuthorization();

// Outbound path to the EventStore gateway via this app's DAPR sidecar. The caller's validated bearer is
// forwarded unchanged so EventStore's JWT/RBAC/tenant enforcement stays authoritative. A literal
// localhost base address keeps the global AddServiceDiscovery() default a no-op.
string daprHttpEndpoint = DaprHttpEndpointResolver.Resolve(builder.Configuration);
string? daprApiToken = builder.Configuration["DAPR_API_TOKEN"];

builder.Services.AddTransient<InboundBearerForwardingHandler>();
builder.Services.AddEventStoreGatewayClient(options => options.BaseAddress = new Uri(daprHttpEndpoint))
    .AddHttpMessageHandler<InboundBearerForwardingHandler>()
    .AddHttpMessageHandler(() => new DaprAppIdHandler("eventstore", daprApiToken));

// AD-17: opt into the absolute command-status Location header when a browser-facing gateway origin is
// configured. When the value is absent or malformed the AddEventStoreGatewayClient fail-closed default
// applies (generated command 202 responses emit no Location header).
// The guard mirrors AddEventStoreCommandStatusLocation's own validation (absolute http(s) origin, no user
// info / query / fragment) so a malformed config value is skipped (fail-closed default applies) rather than
// throwing inside the extension and crashing host startup.
string? gatewayStatusBase = builder.Configuration["EventStore:GatewayStatusBase"]?.Trim();
if (!string.IsNullOrWhiteSpace(gatewayStatusBase)
    && Uri.TryCreate(gatewayStatusBase, UriKind.Absolute, out Uri? gatewayStatusBaseUri)
    && (gatewayStatusBaseUri.Scheme == Uri.UriSchemeHttp || gatewayStatusBaseUri.Scheme == Uri.UriSchemeHttps)
    && string.IsNullOrEmpty(gatewayStatusBaseUri.UserInfo)
    && string.IsNullOrEmpty(gatewayStatusBaseUri.Query)
    && string.IsNullOrEmpty(gatewayStatusBaseUri.Fragment)) {
    builder.Services.AddEventStoreCommandStatusLocation(gatewayStatusBaseUri);
}

WebApplication app = builder.Build();

if (!app.Environment.IsDevelopment()) {
    _ = app.UseHsts();
}

app.UseHttpsRedirection();
app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();
app.MapDefaultEndpoints();

app.Run();

/// <summary>
/// Entry point class, made partial for WebApplicationFactory test access.
/// </summary>
public partial class Program;
