using Hexalith.EventStore.Admin.Cli.Commands.Config;

namespace Hexalith.EventStore.Admin.Cli.Tests.Commands.Config;

/// <summary>
/// Direct unit tests for CompletionScripts static generators.
/// Complements ConfigCompletionCommandTests which tests via the command dispatch path.
/// </summary>
public class CompletionScriptsTests {
    // === Date header ===

    [Theory]
    [InlineData("Bash")]
    [InlineData("Zsh")]
    [InlineData("PowerShell")]
    [InlineData("Fish")]
    public void AllShells_ContainGeneratedDateHeader(string shell) {
        string output = GenerateForShell(shell);

        output.ShouldContain("Generated by eventstore-admin");
        output.ShouldContain(DateTime.UtcNow.ToString("yyyy-MM-dd"));
    }

    // === Profile subcommands ===

    [Theory]
    [InlineData("Bash")]
    [InlineData("PowerShell")]
    [InlineData("Fish")]
    public void Shells_ContainProfileSubcommands(string shell) {
        string output = GenerateForShell(shell);

        output.ShouldContain("add");
        output.ShouldContain("list");
        output.ShouldContain("show");
        output.ShouldContain("remove");
    }

    // === Format values ===

    [Theory]
    [InlineData("Bash")]
    [InlineData("Zsh")]
    [InlineData("PowerShell")]
    [InlineData("Fish")]
    public void AllShells_ContainFormatValues(string shell) {
        string output = GenerateForShell(shell);

        output.ShouldContain("json");
        output.ShouldContain("csv");
        output.ShouldContain("table");
    }

    // === Completion shell choices ===

    [Theory]
    [InlineData("Bash")]
    [InlineData("PowerShell")]
    [InlineData("Fish")]
    public void CompletionShellChoices_Present(string shell) {
        string output = GenerateForShell(shell);

        output.ShouldContain("bash");
        output.ShouldContain("zsh");
        output.ShouldContain("powershell");
        output.ShouldContain("fish");
    }

    // === Config subcommands ===

    [Theory]
    [InlineData("Bash")]
    [InlineData("Zsh")]
    [InlineData("PowerShell")]
    [InlineData("Fish")]
    public void AllShells_ContainConfigSubcommands(string shell) {
        string output = GenerateForShell(shell);

        output.ShouldContain("profile");
        output.ShouldContain("use");
        output.ShouldContain("current");
        output.ShouldContain("completion");
    }

    // === PowerShell uses USERPROFILE, others use HOME ===

    [Fact]
    public void PowerShell_UsesUserProfileEnvVar() {
        string output = CompletionScripts.GeneratePowerShell();

        output.ShouldContain("$env:USERPROFILE");
    }

    [Theory]
    [InlineData("Bash")]
    [InlineData("Zsh")]
    [InlineData("Fish")]
    public void UnixShells_UseHomeEnvVar(string shell) {
        string output = GenerateForShell(shell);

        output.ShouldContain("HOME");
    }

    // === Command-specific subcommands ===

    [Theory]
    [InlineData(
        "Bash",
        "        backup)\n            COMPREPLY=( $(compgen -W \"create restore list\" -- \"${cur}\") );;",
        "        tenant)\n            COMPREPLY=( $(compgen -W \"list detail users verify\" -- \"${cur}\") );;")]
    [InlineData(
        "Zsh",
        "                backup) compadd create restore list;;",
        "                tenant) compadd list detail users verify;;")]
    [InlineData(
        "PowerShell",
        "        'backup' { 'create', 'restore', 'list' }",
        "        'tenant' { 'list', 'detail', 'users', 'verify' }")]
    [InlineData(
        "Fish",
        "complete -c eventstore-admin -n '__fish_seen_subcommand_from backup; and not __fish_seen_subcommand_from create restore list' -a 'create restore list'",
        "complete -c eventstore-admin -n '__fish_seen_subcommand_from tenant; and not __fish_seen_subcommand_from list detail users verify' -a 'list detail users verify'")]
    public void AllShells_PinBackupAndTenantInventoriesToTheirCommandScopes(
        string shell,
        string expectedBackupStanza,
        string expectedTenantStanza) {
        string output = GenerateForShell(shell);

        CountOccurrences(output, expectedBackupStanza).ShouldBe(1);
        CountOccurrences(output, expectedTenantStanza).ShouldBe(1);
        output.ShouldNotContain("export-stream");
        output.ShouldNotContain("import-stream");
    }

    // === Helper ===

    private static string GenerateForShell(string shell) => shell switch {
        "Bash" => CompletionScripts.GenerateBash(),
        "Zsh" => CompletionScripts.GenerateZsh(),
        "PowerShell" => CompletionScripts.GeneratePowerShell(),
        "Fish" => CompletionScripts.GenerateFish(),
        _ => throw new ArgumentException($"Unknown shell: {shell}"),
    };

    private static int CountOccurrences(string value, string expected)
        => value.Split(expected, StringSplitOptions.None).Length - 1;
}
