namespace Hexalith.EventStore.Admin.UI.E2E;

/// <summary>
/// Browser render-smoke matrix + high-value interaction flows for Admin.UI, generated by the
/// TEA <c>*automate</c> workflow (coverage plan: <c>_bmad-output/test-artifacts/automation-summary.md</c>).
///
/// <para>
/// The shared <see cref="PlaywrightFixture"/> boots Admin.UI <b>standalone with no backend API</b>,
/// so every test asserts render / navigation / interaction only — never live data. The fixture's
/// SignalR client and dashboard polling target an absent backend, so the browser console carries
/// connection/resource noise on every page; <see cref="IsInfrastructureNoise"/> filters that out so
/// the assertion keeps only genuine JS / Blazor render errors (the render-loop signal the DW5 tests
/// also guard).
/// </para>
/// </summary>
/// <remarks>
/// Render waits intentionally use Playwright's default timeout rather than a short wall-clock budget:
/// a route's first server-render + hydration pays cold JIT, and the 2026-05-25 framework audit (Q3)
/// proved fixed perf budgets flake on cold start. Perf budgets are owned by perf-lab.yml.
/// </remarks>
[Trait("Category", "E2E")]
[Collection("Playwright")]
public class RouteRenderSmokeTests
{
    private static readonly TimeSpan _interactionTimeout = TimeSpan.FromSeconds(5);

    private readonly PlaywrightFixture _fixture;

    public RouteRenderSmokeTests(PlaywrightFixture fixture) => _fixture = fixture;

    // RSMOKE-01..20 — every nav-reachable route renders its page shell.
    // The dashboard ("/") and StreamDetail ("/streams/{tenant}/{domain}/{aggregate}") are excluded:
    // "/" is covered by BrowserSmokeTests; StreamDetail needs seeded IDs the no-backend fixture lacks.
    [Theory]
    [InlineData("/commands", "Commands")]
    [InlineData("/events", "Events")]
    [InlineData("/streams", "Streams")]
    [InlineData("/health", "Health")]
    [InlineData("/health/dead-letters", "Dead Letters")]
    [InlineData("/dapr", "DAPR Infrastructure")]
    [InlineData("/dapr/actors", "DAPR Actor Inspector")]
    [InlineData("/dapr/health-history", "DAPR Health History")]
    [InlineData("/dapr/pubsub", "DAPR Pub/Sub Delivery Metrics")]
    [InlineData("/dapr/resiliency", "DAPR Resiliency Policies")]
    [InlineData("/projections", "Projections")]
    [InlineData("/types", "Type Catalog")]
    [InlineData("/services", "Services")]
    [InlineData("/tenants", "Tenants")]
    [InlineData("/storage", "Storage")]
    [InlineData("/snapshots", "Snapshots")]
    [InlineData("/compaction", "Compaction")]
    [InlineData("/backups", "Backups")]
    [InlineData("/consistency", "Consistency")]
    [InlineData("/settings", "Settings")]
    public async Task Route_RendersHeadingAndMainLandmark_WithoutRenderErrors(string route, string expectedHeading)
    {
        (IBrowserContext context, IPage page) = await _fixture.CreatePageAsync();
        List<string> errors = [];
        page.Console += (_, msg) =>
        {
            if (msg.Type == "error" && !IsInfrastructureNoise(msg.Text))
            {
                errors.Add(msg.Text);
            }
        };

        await using (context)
        {
            await page.GotoAsync(route);

            // Hydration signal: the layout's main landmark is present.
            await page.WaitForSelectorAsync("main[role='main']");

            // The page's own H1 renders (proves the route resolved to its component, not a 404/blank shell).
            await page.WaitForSelectorAsync($"h1:has-text(\"{expectedHeading}\")");

            errors.ShouldBeEmpty(
                customMessage: $"Render errors on {route}: {string.Join(" | ", errors)}");
        }
    }

    // FLOW-01 — Theme toggle cycles System → Light and persists to localStorage across a reload.
    [Fact]
    public async Task ThemeToggle_CyclesToLightAndPersistsAcrossReload()
    {
        const string themeKey = "hexalith-admin-theme";

        (IBrowserContext context, IPage page) = await _fixture.CreatePageAsync();
        await using (context)
        {
            await page.GotoAsync("/");

            // Default ThemeState.Mode is System, so the toggle offers "Switch to light theme".
            ILocator toggle = page.Locator("[aria-label='Switch to light theme']");
            await toggle.WaitForAsync(new LocatorWaitForOptions
            {
                State = WaitForSelectorState.Visible,
                Timeout = (float)_interactionTimeout.TotalMilliseconds,
            });

            await toggle.ClickAsync();

            // The click cycles to Light and writes the choice through JS interop.
            await page.WaitForFunctionAsync(
                "(args) => localStorage.getItem(args.key) === 'Light'",
                new { key = themeKey },
                new PageWaitForFunctionOptions { Timeout = (float)_interactionTimeout.TotalMilliseconds });

            // The button's affordance now advances to the next mode in the cycle (Light → Dark).
            await page.Locator("[aria-label='Switch to dark theme']").WaitForAsync(new LocatorWaitForOptions
            {
                State = WaitForSelectorState.Visible,
                Timeout = (float)_interactionTimeout.TotalMilliseconds,
            });

            // Persistence contract: a reload restores Light from localStorage.
            await page.ReloadAsync();
            await page.WaitForSelectorAsync("main[role='main']");

            string? restored = await page.EvaluateAsync<string?>(
                "(args) => localStorage.getItem(args.key)",
                new { key = themeKey });
            restored.ShouldBe("Light",
                customMessage: "Theme choice must survive a reload via localStorage.");

            await page.Locator("[aria-label='Switch to dark theme']").WaitForAsync(new LocatorWaitForOptions
            {
                State = WaitForSelectorState.Visible,
                Timeout = (float)_interactionTimeout.TotalMilliseconds,
            });
        }
    }

    // FLOW-02 — Command palette search narrows the catalog to the matching entry.
    // Distinct aspect from Dw5SidebarShortcut AC#7 (open/close/reopen): this exercises the typed
    // search + CommandPaletteCatalog.Filter wired through the live Fluent input. Result-click
    // navigation is intentionally not asserted here — it overlaps the nav coverage in
    // BrowserSmokeTests and the dialog-close+navigate path is non-deterministic to drive.
    [Fact]
    public async Task CommandPalette_SearchNarrowsToMatchingEntry()
    {
        (IBrowserContext context, IPage page) = await _fixture.CreatePageAsync();
        await using (context)
        {
            await page.GotoAsync("/");
            await page.WaitForSelectorAsync(".admin-sidebar nav[aria-label='Main navigation']");
            await WaitForShortcutRegistrationAsync(page);

            await page.Keyboard.PressAsync("Control+k");

            ILocator search = page.Locator("input[placeholder='Search commands, pages, actions...']").First;
            await search.WaitForAsync(new LocatorWaitForOptions
            {
                State = WaitForSelectorState.Visible,
                Timeout = (float)_interactionTimeout.TotalMilliseconds,
            });

            // A full unique label filters CommandPaletteCatalog to exactly one entry.
            await search.FillAsync("Storage Growth Analyzer");

            // FluentTextInput binds @bind-Value on the change event (no Immediate), which fires on
            // blur — so the search only filters after the field loses focus.
            await search.BlurAsync();

            // Result buttons live in the dialog body; the clear-search button is excluded by label.
            ILocator results = page.Locator(
                "[aria-label='Command palette'] fluent-button:not([aria-label='Clear search'])");

            // Auto-retry until the search has narrowed to the single matching result.
            await Assertions.Expect(results).ToHaveCountAsync(1, new LocatorAssertionsToHaveCountOptions
            {
                Timeout = (float)_interactionTimeout.TotalMilliseconds,
            });

            string resultText = await results.First.InnerTextAsync();
            resultText.ShouldContain("Storage Growth Analyzer");
        }
    }

    // FLOW-03 — Breadcrumb reflects the current route (Home link + current-page marker).
    [Fact]
    public async Task Breadcrumb_ReflectsCurrentRoute()
    {
        (IBrowserContext context, IPage page) = await _fixture.CreatePageAsync();
        await using (context)
        {
            await page.GotoAsync("/events");
            await page.WaitForSelectorAsync("main[role='main']");

            ILocator breadcrumb = page.Locator("nav[aria-label='Breadcrumb']");
            await breadcrumb.WaitForAsync(new LocatorWaitForOptions
            {
                State = WaitForSelectorState.Visible,
                Timeout = (float)_interactionTimeout.TotalMilliseconds,
            });

            // Home is a navigable ancestor segment.
            (await breadcrumb.Locator("a:has-text('Home')").CountAsync()).ShouldBeGreaterThan(0);

            // The current route is marked aria-current="page" with its breadcrumb label.
            string currentText = await breadcrumb.Locator("[aria-current='page']").InnerTextAsync();
            currentText.ShouldContain("Events");
        }
    }

    /// <summary>
    /// True for console errors caused by the fixture's missing backend (SignalR hub unreachable,
    /// dashboard-poll/static-asset fetch failures) rather than a genuine client-side JS / Blazor
    /// render fault. Filtering these keeps the render-error assertion meaningful in a no-backend host.
    /// </summary>
    private static bool IsInfrastructureNoise(string text)
    {
        ReadOnlySpan<string> noiseMarkers =
        [
            "Failed to load resource",
            "net::ERR",
            "ERR_CONNECTION",
            "WebSocket",
            "signalr",
            "negotiate",
            "Failed to fetch",
        ];

        foreach (string marker in noiseMarkers)
        {
            if (text.Contains(marker, StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }

        return false;
    }

    /// <summary>
    /// Waits until MainLayout's <c>hexalithAdmin.registerShortcuts</c> hydration call has registered
    /// the Ctrl+K / Ctrl+B handlers, so a keypress is not dropped before the circuit is ready.
    /// </summary>
    private static async Task WaitForShortcutRegistrationAsync(IPage page)
    {
        await page.WaitForFunctionAsync(
            "() => window.hexalithAdmin?._shortcutHandlers?.size > 0",
            options: new PageWaitForFunctionOptions { Timeout = (float)_interactionTimeout.TotalMilliseconds });
    }
}
