<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup Condition="'$(UseCurrentSource)' != 'true'">
    <PackageReference Include="Hexalith.EventStore.DomainService" />
  </ItemGroup>
  <ItemGroup Condition="'$(UseCurrentSource)' == 'true'">
    <ProjectReference Include="$(EventStoreSourceRoot)/src/Hexalith.EventStore.DomainService/Hexalith.EventStore.DomainService.csproj" />
  </ItemGroup>
</Project>
