<Project><PropertyGroup><ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally></PropertyGroup><ItemGroup><PackageVersion Include="Hexalith.EventStore.Client" Version="[3.115.0]" /><PackageVersion Include="Hexalith.EventStore.Contracts" Version="[3.115.0]" /><PackageVersion Include="Hexalith.EventStore.DomainService" Version="[3.115.0]" /><PackageVersion Include="Hexalith.EventStore.Server" Version="[3.115.0]" /><PackageVersion Include="Hexalith.EventStore.ServiceDefaults" Version="[3.115.0]" /></ItemGroup></Project>
