name: 'Initialize .NET Framework'
description: 'Sets up .NET SDK 10.0.300 and installs Aspire workload'
inputs:
  aspire:
    description: 'Whether to install Aspire workload'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Setup .NET 10.0.300
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.300
    - name: Add Aspire Workloads
      if: inputs.aspire != ''
      shell: bash
      run: dotnet workload install aspire 
